### ISSUE TITLE
O> How best to organize the /Members repo

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#105]
_oops! scope of this issue has gotten muddy. Use of labels should be split out from how to organize files in the repo. And "use of labels" is not SMART either; I'm noodling on how to attack it._

One of my goals for this issue in particular is:
 - [ ] establish pull request workflow with reviews (_done in #319_)

Stuff for an issue to-be-created:

  - [ ] close issues that have no clear next steps, after allowing a two or three weeks for brainstorming (_see #401_)
  - [ ] mark them **needs-SMART-objective** a few days before closing
  - for example:
    - [ ] #189 governance agenda - overtaken by

**Comment by lapin7** [comment]
@dckc It would indeed be better if things are split up in different projects. Please make a proposal and let's see how we can implement this. Probably you're more experienced in Github then I am ;-)
The goal is to make things manageable and workable for collaborators.

**Comment by dckc** [comment]
Well, I propose:
  - @kitblake creates a repo for welcomebot: https://github.com/kitblake/welcomebot and moves the contents of https://github.com/rchain/Members/tree/master/projects/bots/welcomebot there
    - peers can fork that repo as usual...
    - if / when it becomes important for there to be a "master" repo that isn't owned by kitblake, create `/rchain/welcomebot`
  - @jimscarver (or anyone else... me, even) move https://github.com/rchain/Members/blob/master/projects/identity/userstory.md to the wiki (in my experience, user stories work well in a wiki). If it starts to take the form of a piece of software, that can happen in a new repo, and relevant wiki pages can be migrated or cross-linked.
  - @kitblake (or anybody... me...) move `/projects/dictionary.md` to just `/dictionary.md`... though until it matures a bit, I think a branch other than `master` would be best.

Then delete `/projects`

**Comment by jimscarver** [comment]
@dckc how does one find projects related to rchain member activities. It is convenient to find them the under projects. I guess we could just have a projects file that points to them. We put it unders /members because the community only has access there.

**Comment by dckc** [comment]
Yes, you link to them from a projects file (or wiki topic).

The awkward thing about the current arrangement is: if you want to clone any of the projects, you end up cloning them all. And a commit to one has to be sync'd (push / pull) by all, and so on.

**Comment by kitblake** [comment]
/projects was created to keep the root of /Members clean. It's also where things-being-incubated live before they move to a permanent home, e.g. the FAQ was in /Members/projects before it was ready for prime time. Then it moved to the public facing /reference. Presumably dictionary.md will do the same.

As for the three reorganization points:
1. I don't want to own the Welcome Bot because I didn't write it. @jimscarver wrote it, but it really is a community project. Albeit a little one.
2. The Identity project user story is already in the wiki so that folder can be deleted. If the Identity project creates code someday we'll figure out where it should live then.
3. dictionary.md should stay in master because other people need to find and contribute to it. I'm not technical so educated contributions are sorely needed.

We can go "Flat is better than nested" but let's not have a /Members root full of defunct project repos. We want visitors to read the congenial README and if it's below the window horizon they won't scroll and find it.

Maybe we should just rename 'projects' to 'incubation' so it's obviously temporary.

**Comment by dckc** [comment]
things-being-incubated belong on branches

**Comment by jimscarver** [comment]
living documents are not being incubated they are being evolved. It may be
the wiki is a better place for those.

We want things in the same place to facilitate working together community
wide. Branches in members are for individuals or small teams working
independently. External branches are good for starting experimental stuff
but need to be brought in to get wider community participation.

The process of organizing github is the larger issue we might create a team
to oversee starting with ourselves. Onboarding/process/norms documentation
would be a deliverable in addition to the reorganization.  Can anyone
suggest a budget for this?

**Comment by dckc** [comment]
@kitblake you didn't write welcomebot? The git history strongly suggests you did... but now I see that you moved it from something that @jimscarver commited. That's one reason to use branches rather than subdirectories: git isn't very good at tracking history when things move around. Hmm... maybe it does better than I thought; blame shows most of lines as written by @jimscarver.

Still: renames / moves are expensive. For example, they tend to break incoming web links to this gihub view of the repo.

And yes, onboarding docs -- and rituals -- are worth investing in. That's why I put some effort into CONTRIBUTING.md. But there's plenty more to be done.

**Comment by kitblake** [comment]
@dkkc thanks for your input on this Github usage question. We discussed it during the weekly Activist meeting but didn't arrive at any conclusions.

The /Members repo is not populated with engineers and there's no appreciable code base yet. Considering onboarding and the fostering of community activism we want to keep everything visible. Hiding stuff in branches makes sense given a mature code base but that's not the situation here. We want new people to find and jump into ongoing projects or initiate their own.

The content that is code, like the Welcome Bot. is minimal. The bot consists of a script and an icon. It doesn't warrant having a whole repository. (Yes, blame @jimscarver for the implementation, and me for the content and behavior). If anybody wants to fork it they can just copy the script but it's pretty RChain specific.

Developing documents like the FAQ or Dictionary in a wiki context has its upsides and downsides. Personally I prefer the checkin with comment process for tracking the history.

**Comment by kitblake** [comment]
Following on @jimscarver's suggestion I edited @dckc's issue title (also it exceeded the Github recommended 50 character summary limit ;)

**Comment by lapin7** [comment]
@dckc @jimscarver @kitblake Please don't forget to add a budget through form [Budget allocation and spending](https://docs.google.com/forms/d/e/1FAIpQLSfz-EGexMGPaw0eHwlBBNssQIR5hQCEOsWOZceVrPCo5mjGUA/viewform)


URL | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | $ Sep Budget | ⍴ Sep Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/105 | New | How best to organize the /Members repo | Marketing | 0 | $ - | $ - | $ - | $ - | ⍴ - |  


And please distribute the budget over the assigned collaborators.


https://github.com/rchain/Members/issues/105 | How best to organize the /Members repo | Marketing | 0 | New | ⍴ - | $ - | $ - | $ - | Activist | 0% | 0 | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/105 | How best to organize the /Members repo | Marketing | 0 | New | ⍴ - | $ - | $ - |   | @dckc | 0% | 0 |  
https://github.com/rchain/Members/issues/105 | How best to organize the /Members repo | Marketing | 0 | New | ⍴ - | $ - | $ - |   | @kitblake | 0% | 0 |  
https://github.com/rchain/Members/issues/105 | How best to organize the /Members repo | Marketing | 0 | New | ⍴ - | $ - | $ - |   | jimscarver | 0% | 0 |

**Comment by lapin7** [comment]
**Budget update**
**2 more Activists votes needed for setting the budget** (please find them :-)


URL | Status | Project / Issue | Category | Votes | Last month | Left over | New Budget | $ Sep Budget | ⍴ Sep Budget | Voters
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
https://github.com/rchain/Members/issues/105 | New | How best to organize the /Members repo | Marketing | 1 | $ - | $ - | $ 100.00 | $ 100.00 | ⍴ 1,000.00 | @kitblake

**Comment by dckc** [comment]
The `projects` directory just won't die. :)

I just discovered https://github.com/rchain/Members/blob/master/projects/LinksToOfficialChannels.md ; it seems to have a lot of overlap with https://github.com/rchain/Members/wiki/Channels-Moderators . Isn't a wiki page a lot easier?

(also: what makes those channels "official"? Has the board approved them, directly or indirectly?)

**Comment by dckc** [comment]
Why a [membership directory](https://github.com/rchain/Members/tree/master/membership) in a `Members` repo?

The department of redundancy department strikes again :)

**Comment by dckc** [comment]
Many of the [projects](https://github.com/rchain/Members/projects) are more like categories; e.g. "Event Coordination" and "". We should use labels for those. Projects are things that we expect to finish.

This one is a project, but it's coordinated elsewhere:
 1. Rosette-VM

This one is perhaps a project, though the description says otherwise:
 1. Identity on RChain

The names and descriptions of these make it clear that they're not projects:
 1. Digital Community Building
 1. Outreach & Social Media
 1. Event Coordination
 1. Content Creation
 1. Compensation Committee
 1. Graphic Designs
 1. Website Coordination
    - perhaps this should be re-scoped as a project for the v3 web site redesign (#156, #145, ...) 
 1. Governance Committee
 1. Executive Committee
 1. Organizational frameworking

**Comment by dckc** [comment]
@patrick727 you asked (in discord) what happened to the [content creation project](https://github.com/rchain/Members/projects/11). I closed it, as described above. It's still there, so no information is lost. But projects should be for things we expect to finish, not just ways to categorize things. To categorize things, use labels.

One thing that projects have that labels don't have is a way to visualize (and limit) the amount of work going through a process. Were you using that aspect of github projects?

**Comment by lapin7** [comment]
If you use ZenHub Chrome extension.
https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd
Then you have also KanBan project management style.


--
Cheers,
HJ

**Comment by dckc** [comment]
The number of translation issues is exciting!

My eyes are starting to glaze over the **Marketing** label on so many issues. Does anyone review all the Marketing issues or something?

I suggest that a translation into Chinese be labelled **Translation** and **China**. An event in China would be labelled **Events** and **China**. That way someone who notices a Chinese translation might easily find their way to an event in China, and vice versa.

_p.s. China is so large that the notion of "all events in China" will surely become silly before long, if we're successful; please excuse my American-centric writing for now._

**Comment by BelovedAquila** [comment]
@dckc not a bad suggestion, but is it label China on the basis of China having a broad future prospects as partains to rchain or just for the sake of clarity of issues?

**Comment by dckc** [comment]
"Chinese" would make sense if it were only about translation, @BelovedAquila. But it's about events and such too. Broad future prospects, as you put it. As noted in a recent weekly debrief, @llerner is making a lot of contacts there.

To my mind, clarity of issues and broad future prospects go hand in hand; I don't see how or why to separate them.

**Comment by BelovedAquila** [comment]
@dckc alright. I now understand on a broader perspective what you are trying to pass across.

**Comment by dckc** [comment]
For reference... I asked a few times: why add the M> prefix? Is there some automated process that consumes it?

@lapin7 replied [Feb 2][]:
> A cell calcs M> to Marketing
> And it's used for bookaccounting purpose

The convention dates back as far as [Dec 8][]. I thought it had been subsumed by github labels, but apparently not.

[Feb 2]: https://github.com/rchain/Members/issues/279#issuecomment-362682280
[Dec 8]: https://github.com/rchain/Members/issues/165#issuecomment-350388332

**Comment by lapin7** [comment]
We can skip the M> again and stick to labels.
It's standard functionality and it gives us back 3 chars from the title.
Can you add the first label of an issue to the output of the script?

--
Cheers,
HJ

**Comment by dckc** [comment]
Yes, I can script something like that.

I would like to understand better how the information is consumed.
