### ISSUE TITLE
M> Translate README.md to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#286]
**Completed:** 100%

**Tasks:**
- [x] Create the file [README_GR.md](https://github.com/rchain/bounties/blob/master/README/README_GR.md)
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Greek

**Collaborators Work:**
- @ICA3DaR5: 50%
- @zero-andreou: 25%
- @thiefinshadows: 25%

**Suggested Budget:** $100

**Comment by ICA3DaR5** [comment]
I think this has been completed.
