### ISSUE TITLE
M> Translate Rchain/reference/faq.md to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#299]
**Completed:** 100%

**Tasks:**
- [x] Create the file [faq_gr.md](https://github.com/ICA3DaR5/reference/blob/patch-1/faq_gr.md)
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Greek
- [x] Create a [Pull Request](https://github.com/rchain/reference/pull/42)

**Collaborators Work:**
- @ICA3DaR5: 40%
- @zero-andreou: 30%
- @thiefinshadows: 30%

**Suggested Budget:** $500

**Comment by ICA3DaR5** [comment]
This is finished!
