### ISSUE TITLE
M> Translate /rchain/rholang/doc/* to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#345]
**Completed:** 100%

**Tasks:**
- [x] Create the file [rholangtut-0.1_GR.md](https://github.com/ICA3DaR5/rchain/blob/Issue-%23345/rholang/doc/rholangtut-0.1_GR.md)
- [x] Create the file [rholangtut-mercury_GR.md](https://github.com/ICA3DaR5/rchain/blob/Issue-%23345/rholang/doc/rholangtut-mercury_GR.md)
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Greek
- [x] Create a [Pull Request](https://github.com/rchain/rchain/pull/295)

**Collaborators Work:**
- @ICA3DaR5: 40%
- @zero-andreou: 30%
- @thiefinshadows: 30%

**Suggested Budget:** $1700

**Comment by ICA3DaR5** [comment]
Should we start translating this?

**Comment by lapin7** [comment]
Try to create an issue. See if you can get support of two others for
setting the budget. If so, go ahead.

--
Cheers,
HJ

**Comment by ICA3DaR5** [comment]
No, but I intent to maintain them. All of the work we do actually.

**Comment by ICA3DaR5** [comment]
This is finished.

**Comment by dckc** [comment]
It's great to see this progress, but until PR295 is merged, let's keep this open.

I still don't see any indication that the core team wants a greek translations at this time. See #184 on collaborating with the core dev team.
