### ISSUE TITLE
M> Translate /Rchain/Rholang/Doc/* to Italian

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#367]
**Completed:** 100%

**Tasks:**
- [x] Create the file [rholangtut-0.1_IT.md](https://github.com/rchain/rchain/blob/dev/rholang/doc/rholangtut-0.1_IT.md)
- [x] Create the file [rholangtut-mercury_IT.md](https://github.com/rchain/rchain/blob/dev/rholang/doc/rholangtut-mercury_IT.md)
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Italian
- [x] Create a [Pull Request](https://github.com/rchain/rchain/pull/325)

**Collaborators Work:**
- @Staff91: 50%
- @akhs13 : 20%
- @Chris-Arv : 30%

**Suggested Budget:** $1800

**Comment by Staff91** [comment]
This is finished as well!

**Comment by Staff91** [comment]
Update documents.

**Comment by Staff91** [comment]
After carefully reviewing the Rholang Doc files with my collaborators @Chris-Arv @akhs13  we have arrived to the conclusion that there are no changes in the files and that no further pull request is necessary. @dckc
