### ISSUE TITLE
M> Translate Architecture-docs/*.rst files to Italian

### ISSUE THREAD

**Issue by ghost** [rchain/bounties#368]
**Completed:** 100%

**Tasks:**
- [x] Create the .rst files
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Italian
- [x] Create a [Pull Request](https://github.com/rchain/architecture-docs/pull/16)

**Collaborators Work:**
- @Staff91: 50%
- @akhs13 : 30%
- @Chris-Arv : 20%

**Suggested Budget:** $4066,66

**Comment by AbnerZheng** [comment]
Hi, please follow the way as https://github.com/AbnerZheng/mobile-process-calculi-for-blockchain#add-new-language said. Only in this way can your language version be displayed in the readthedoc website.

**Comment by Staff91** [comment]
After carefully reviewing the Architecture-docs files with my collaborators @Chris-Arv @akhs13 we have arrived to the conclusion that there are no changes in the files and that no further pull request is necessary. @dckc

**Comment by dckc** [comment]
I don't see Italian next to English and Chinese in http://arch-doc.rchain.coop/ . Hiw does the audience see your work?

**Comment by Staff91** [comment]
@dckc It should be setup in the next few hours. It needs to get build with Sphinx.

**Comment by AbnerZheng** [comment]
@Staff91 As I know, I am afraid it will never get build.  I will update the document showing how to set up.

**Comment by Staff91** [comment]
Ok, thank you very much!

**Comment by Staff91** [comment]
@AbnerZheng Any updates? Should I do anything?

@dckc

**Comment by dckc** [comment]
I still don't see Italian next to English and Chinese in http://arch-doc.rchain.coop/ .

But I can follow up on that in the context of #580.

**Comment by ICA3DaR5** [comment]
Reopening this for the same reason @dckc mentioned.
