### ISSUE TITLE
M> Translate /reference/docs/RChainWhitepaper.pdf to Italian

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#369]
**Completed:** 100%

**Tasks:**
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Italian
- [x] Create the .pdf file
- [x] Create a [Pull Request](https://github.com/rchain/reference/pull/44)

**Collaborators Work:**
- @Staff91: 50%
- @akhs13 : 25%
- @Chris-Arv : 25%

**Suggested Budget:** $3733,33

**Comment by Staff91** [comment]
This is finished!

**Comment by n10n** [comment]
Completed the pull request.
