### ISSUE TITLE
M> Translate Medium Blog Posts to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#390]
**Completed:** 99%

**Tasks:**
- [x] Copy the posts to text files.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Greek.
- [x] Post them to the Greek [Medium](https://medium.com/@rchain.gr) account.
- [x] Post them to the Greek [Facebook](https://www.facebook.com/rchain.gr/), [Twitter](https://twitter.com/rchain_gr) and [Telegram](https://t.me/rchain_gr) accounts.

**Collaborators Work:**
- @ICA3DaR5: 40%
- @zero-andreou: 30%
- @thiefinshadows: 29%

**Suggested Budget:** $2000

**Comment by dckc** [comment]
A translation of a blog item should be published as a blog item, right? I don't see how putting them in a google drive folder gets them out to an audience.

@patrick727 do you have any suggestions for where to put Greek translations? (He's a [moderator](https://github.com/rchain/bounties/wiki/Channels-Moderators) for medium.)

Does medium have any sort of multi-language support?

Should @ICA3DaR5 make a separate blog?

**Comment by ICA3DaR5** [comment]
@dckc I was thinking of making a website (I am a full-stack developer).

I was thinking of translating them first and then create the website with a blog. OR I could create a Greek Medium account.

**Comment by dckc** [comment]
This is 80% done? I don't see any results. I don't think the Feb budget should be $2000.

**Comment by jplepel** [comment]
Gave a look at the Rchain Greek twitter account. 1 follower. For a fairly large bounty, can you focus on marketing Rchain to the Greek market as well? Chicken and the Egg situation, but would like to know there is a market demand for Greek documents.

**Comment by ICA3DaR5** [comment]
@dckc I am uploading the articles now.

**Comment by ICA3DaR5** [comment]
@jplepel I intend to market those channels once I create a website for this.
