### ISSUE TITLE
M> Translate "Rchain Exclusive chat Lawrence Lerner & Nash Foster" Transcript to Italian

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#392]
**Completed:** 100%

**Tasks:**
- [x] Download the video
- [x] Download the English (original) transcript
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] View video with the Italian transcript and review
- [x] Have it reviewed by others with knowledge of English and Italian
- [x] Upload the Italian (translated) transcript, [here](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)

**Collaborators Work:**
- @Staff91: 40%
- @akhs: 20%
- @Chris-Arv : 40%

**Suggested Budget**: $4500

Google Document: https://drive.google.com/open?id=1qx6eMaE6LHotPrnbtsgsS-_h-6FEh0IW3sv-bx3Cuzs
SRT File: https://drive.google.com/open?id=1pBrN6ESjPatZmG0hGGicue8GcOcaZUV9

**Comment by Keaycee** [comment]
@Staff91 This is the original transcript file [here](https://docs.google.com/document/d/1BBfUS2-pHxSHo38rDUUqBmjxjm8HldJvMCKc8Xhiu7g/edit?usp=sharing)

**Comment by Staff91** [comment]
@Keaycee Thanks a lot!

**Comment by Chris-Arv** [comment]
We finished the Italian translation.
