### ISSUE TITLE
Translate the /rchain/mobile-process-calculi-for-blockchain/* documents to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#472]
# Issue

## Original (English) Content
- [mobile-process-calculi-for-blockchain/*](https://github.com/rchain/mobile-process-calculi-for-blockchain)

## Translated (Greek) Content
- [mobile-process-calculi-for-blockchain/*](https://github.com/rchain/mobile-process-calculi-for-blockchain)

## Tasks
- [x] Download the original (English) documents.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Greek.
- [x] Upload the translated (Greek) documents with a [Pull Request](https://github.com/rchain/mobile-process-calculi-for-blockchain/pull/5)

## Collaborators
- @ICA3DaR5: 40%
- @thiefinshadows: 30%
- @zero-andreou: 30%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $2250

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [ ] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Greek developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Greek.
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: Diploma.
    - [x] A track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #540 .

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by ian-bloom** [comment]
The document is over a year old, but is **featured** on an x.rchain.coop website.:

- [https://developer.rchain.coop/faq](https://developer.rchain.coop/faq)
- [https://medium.com/@rchain_coop/mobile-process-calculi-for-programming-the-blockchain-bd67d81643a7](https://medium.com/@rchain_coop/mobile-process-calculi-for-programming-the-blockchain-bd67d81643a7)

[developer.rchain.coop](https://developer.rchain.coop) has not been enabled as a multilingual site, and I don't think Greek is a high priority. At least 51% of Greeks speak English. What are the criteria for selecting content to be translated, and into which languages (translation strategy)?

**Comment by ICA3DaR5** [comment]
@ian-bloom So this is obsolete then?

**Comment by ICA3DaR5** [comment]
This is done, waiting for the Pull Request merge.

**Comment by dckc** [comment]
Wait... how is this done? The audience doesn't get to see it until the PR is merged, right?

**Comment by ICA3DaR5** [comment]
Okay, you are right. I'll leave this open until then.

**Comment by ICA3DaR5** [comment]
I still have no response on the [Pull Request](https://github.com/rchain/mobile-process-calculi-for-blockchain/pull/5)

**Comment by ICA3DaR5** [comment]
This has already been paid for March, putting a 0 budget for May.

Waiting for PR resolution.

**Comment by Viraculous** [comment]
@ICA3DaR5 whats the hitch on this issue? The last comment indicates two months ago.

**Comment by ICA3DaR5** [comment]
@Viraculous As you can see, I didn't receive a reply on the [Pull Request](https://github.com/rchain/mobile-process-calculi-for-blockchain/pull/5) at all!
