### ISSUE TITLE
Translate the remaining /rchain/reference/*.md files to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#475]
# Issue

## Original (English) Content
- [RChainSocialMediaEtiquetteGuidelines.md](https://github.com/rchain/reference/blob/master/RChainSocialMediaEtiquetteGuidelines.md)
- [README.md](https://github.com/rchain/reference/blob/master/README.md)
- [communication_channels.md](https://github.com/rchain/reference/blob/master/communication_channels.md)
- [debrief/20171129.md](https://github.com/rchain/reference/blob/master/debrief/20171129.md)
- [debrief/20171206.md](https://github.com/rchain/reference/blob/master/debrief/20171206.md)
- [finance/rhoc.md](https://github.com/rchain/reference/blob/master/finance/rhoc.md)
- [mediacoverage.md](https://github.com/rchain/reference/blob/master/mediacoverage.md)
- [newsletters/20171214.md](https://github.com/rchain/reference/blob/master/newsletters/20171214.md)
- [newsletters/20180103.md](https://github.com/rchain/reference/blob/master/newsletters/20180103.md)

## Translated (Greek) Content
- [RChainSocialMediaEtiquetteGuidelines_GR.md](https://github.com/rchain/reference/blob/master/RChainSocialMediaEtiquetteGuidelines_GR.md)
- [README_GR.md](https://github.com/rchain/reference/blob/master/README_GR.md)
- [communication_channels_GR.md](https://github.com/rchain/reference/blob/master/communication_channels_GR.md)
- [debrief/20171129_GR.md](https://github.com/rchain/reference/blob/master/debrief/20171129_GR.md)
- [debrief/20171206_GR.md](https://github.com/rchain/reference/blob/master/debrief/20171206_GR.md)
- [finance/rhoc_GR.md](https://github.com/rchain/reference/blob/master/finance/rhoc_GR.md)
- [mediacoverage_GR.md](https://github.com/rchain/reference/blob/master/mediacoverage_GR.md)
- [newsletters/20171214_GR.md](https://github.com/rchain/reference/blob/master/newsletters/20171214_GR.md)
- [newsletters/20180103_GR.md](https://github.com/rchain/reference/blob/master/newsletters/20180103_GR.md)

## Tasks
- [x] Download the original (English) files.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Greek.
- [x] Create a [Pull Request](https://github.com/rchain/reference/pull/48).

## Collaborators
- @ICA3DaR5: 30%
- @thiefinshadows: 30%
- @zero-andreou: 40%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $1400

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [x] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Greek community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Greek.
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: Diploma.
    - [x] A track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447 .

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by ICA3DaR5** [comment]
This is done, waiting for the Pull Request merge.
