### ISSUE TITLE
Translate the remaining /rchain/reference/*.md files to Italian

### ISSUE THREAD

**Issue by akhs13** [rchain/bounties#478]
# Issue

## Original (English) Content
- [rchain-reference/*.md](https://github.com/rchain/reference)

## Translated (Italian) Content
- []()

## Tasks
- [x] Download the original (English) files.
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Italian.
- [ ] Upload the translated files.

## Collaborators
- @akhs13 (Translator): 20%
- @Chris-Arv (Translator): 30%
- @panos1980: (Translator) 0%

## Other Information
- **Completed:** 50%
- **Suggested Budget:** $3000

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [x] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Italian community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Italian.
  - [x] At least two of them have either:
    - [ ] Significant reputation (e.g. a diploma) at stake; source:
    - [x] A track record of quality work on rchain bounties: #367, #368, #369, #392 .

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.
