### ISSUE TITLE
Translate the /rchain/reference/docs/Rosette-1-1.pdf document to Italian

### ISSUE THREAD

**Issue by akhs13** [rchain/bounties#479]
# Issue

## Original (English) Content
- [Rosette-1.1.pdf](https://github.com/rchain/reference/blob/master/docs/Rosette-1.1.pdf)

## Translated (Italian) Content
- []()

## Tasks
- [x] Download the original (English) pdf document.
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have it reviewed by others with knowledge of English and Italian.
- [ ] Upload the translated document.

## Collaborators
- @akhs13 (Translator): 10%
- @Chris-Arv (Translator): 0%
- @Staff91 (Reviewer): 0%

## Other Information
- **Completed:** 10%
- **Suggested Budget:** $5250

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [x] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Italian developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Italian.
  - [x] At least two of them have either:
    - [ ] Significant reputation (e.g. a diploma) at stake; source:
    - [x] A track record of quality work on rchain bounties: #367, #368, #369, #392.

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by Jake-Gillberg** [comment]
I'm not sure that this document is a correct target for translation. Why did you identify it for translation?

To my understanding, the hope is that Rosette is hidden away in the background / might not even be a part of the stack long-term. This document really only seems relevant to the very core development team, which conducts most of its business in English.

**Comment by akhs13** [comment]
@Jake-Gillberg What about #269 and #459 

#269 has been payed.

![screenshot from 2018-03-12 22-56-45](https://user-images.githubusercontent.com/36334774/37309162-b883f5a2-2648-11e8-8e04-c67954f73848.png)

**Comment by Jake-Gillberg** [comment]
My comments also apply to those issues. Putting them there now.

**Comment by ICA3DaR5** [comment]
This document is not to be translated for the time being!
