### ISSUE TITLE
Translate the /rchain/mobile-process-calculi-for-blockchain/* documents to Italian

### ISSUE THREAD

**Issue by akhs13** [rchain/bounties#480]
# Issue

## Original (English) Content
- [mobile-process-calculi-for-blockchain/*](https://github.com/rchain/mobile-process-calculi-for-blockchain)

## Translated (Italian) Content
- []()

## Tasks
- [x] Download the original (English) documents.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Italian.
- [x] Upload the translated documents.
- [x] Creat the [Pull Request](https://github.com/rchain/mobile-process-calculi-for-blockchain/pull/4)

## Collaborators
- @akhs13 (Translator): 40%
- @Chris-Arv (Translator): 30%
- @panos1980 (Translator): 30%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $3000

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [ ] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Italian developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Italian.
  - [x] At least two of them have either:
    - [ ] Significant reputation (e.g. a diploma) at stake; source:
    - [x] A track record of quality work on rchain bounties: #367, #368, #369, #392 .

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by akhs13** [comment]
Finish.

**Comment by ICA3DaR5** [comment]
Please don't close this yet, the [Pull Request](https://github.com/rchain/mobile-process-calculi-for-blockchain/pull/4) is not merged yet.

**Comment by ICA3DaR5** [comment]
This has already been paid in March. Waiting for the PR to merge.

I am putting a 0 budget for May.

**Comment by AyAyRon-P** [comment]
Has the PR happened? We need to close this out - please complete the task. There has been no update in almost 30 days and payment was already delivered in March. 

@akhs13 @Chris-Arv @panos1980 

cc @pavlos1851

**Comment by Viraculous** [comment]
@akhs13is the task completed?

**Comment by akhs13** [comment]
No one has replied on my pull request.

**Comment by Viraculous** [comment]
@akhs13 Ok I see. How can we help? @AyAyRon-P any Idea?
