### ISSUE TITLE
Translate the /rchain/reference/docs/Rosette-1-1.pdf document to Russian

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#481]
# Issue

## Original (English) Content
- [Rosette-1.1.pdf](https://github.com/rchain/reference/blob/master/docs/Rosette-1.1.pdf)

## Translated (Russian) Content
- []()

## Tasks
- [x] Download the original (English) pdf document.
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have it reviewed by others with knowledge of English and Russian.
- [ ] Upload the translated document.

## Collaborators
- @qelentium (Translator): 10%
- @pavlos1851 (Translator): 0%
- @thiefinshadows (Reviewer): 0%

## Other Information
- **Completed:** 10%
- **Suggested Budget:** $5500

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [x] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Russian developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Russian.
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: Diploma.
    - [ ] A track record of quality work on rchain bounties:

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by Jake-Gillberg** [comment]
I'm not sure that this document is a correct target for translation. Why did you identify it for translation?

To my understanding, the hope is that Rosette is hidden away in the background / might not even be a part of the stack long-term. This document really only seems relevant to the very core development team, which conducts most of its business in English.

**Comment by qelentium** [comment]
@Jake-Gillberg this is one of the reference documents. As you can see from here: https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md

**Comment by Jake-Gillberg** [comment]
Thanks for that info. I don't think everything in rchain/reference is important to translate.

**Comment by ICA3DaR5** [comment]
This document is not to be translated for the time being.
