### ISSUE TITLE
M> Translate /reference/docs/RChainWhitepaper.pdf to Russian

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#482]
**Completed:** 100%

**Tasks:**
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Russian
- [x] Create the .pdf file
- [x] Create a [Pull Request](https://github.com/rchain/reference/pull/49)

**Collaborators Work:**
- @qelentium (Translator): 90%
- @pavlos1851 (Translator): 5%
- @thiefinshadows (Reviewer): 5%

**Suggested Budget:** $4000

  - Why this document? (mark all that apply)
    - [x] it's one of the /rchain/reference documents
    - [ ] I contacted the author, who agreed it's important to translate
    - [x] I know a person or audience who would benefit from it: The Russian community.
    - [ ] other: ___
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in Russian
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma.
       - [ ] a track record of quality work on rchain bounties:
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: 29.03.2018

**Comment by Barkov-F** [comment]
Вот перевод [архитектуры Synereo](https://docs.google.com/document/d/1r7g97JCpVbqlg4BJWNSJ177xAhny0h8vWkoGyIS5vEs/edit). Там совпадает больше 80% текста, можно оттолкнуться от этого документа.

**Comment by qelentium** [comment]
Благодарю!  :)))  посмотрю что  к чему!

**Comment by Jake-Gillberg** [comment]
I don't think this issue qualifies as a good translation target under the new [issue template](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md). Unless it is linked to on developer.rchain.coop and I am unaware. It is a bit out of date.

**Comment by qelentium** [comment]
Its already done and tomorrow will be uploaded full work :/

**Comment by qelentium** [comment]
Closed
