### ISSUE TITLE
M>Translate the /rchain/legaldocs* 2 pdf to Italian.

### ISSUE THREAD

**Issue by ghost** [rchain/bounties#489]
# Issue

## Original (English) Content
- [Coop Membership Agreement.pdf](https://github.com/rchain/legaldocs/blob/master/Coop%20Membership%20Agreement.pdf)
- [Token Sale Terms and Conditions.pdf](https://github.com/rchain/legaldocs/blob/master/Token%20Sale%20Terms%20and%20Conditions.pdf)
- [Coop_Membership_Agreement.md](https://github.com/rchain/legaldocs/blob/master/Coop_Membership_Agreement.md)
- [Token_Sale_Terms_and_Conditions.md](https://github.com/rchain/legaldocs/blob/master/Token_Sale_Terms_and_Conditions.md)

## Tasks
- [x] Download the original (English) pdf documents.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have it reviewed by others with knowledge of English and Italian.
- [x] Upload the translated documents.
- [x] Create a [Pull Request](https://github.com/rchain/legaldocs/pull/2)

## Collaborators
- @Staff91 (Translator): 90%
- @akhs13 (Reviewer): 5%
- @Chris-Arv (Reviewer): 5%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $3200
---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [x] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Italian developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Italian.
  - [x] At least two of them have either:
    - [ ] Significant reputation (e.g. a diploma) at stake; source:
    - [x] A track record of quality work on rchain bounties: #367, #368, #369, #392.

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by dckc** [comment]
Translating the legal documents is of questionable value.

I suggest you lower the budget for this work. Note [budget votes][1] from myself, @ian-bloom , @Jake-Gillberg and others.

[1]: https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=489#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-action%3Drelated_records_list%26num%3D%253D489%26-relationship%3DBudgetVotes%26-table%3Dissue%26-ui-root%3Dmain-content%26-cursor%3D0%26-skip%3D0%26-limit%3D30%26-mode%3Dlist

**Comment by Staff91** [comment]
@dckc Hi, i understand absolutely , if the suggested budget is too high, i'm content with lowering it, seeing as we are a coop and everybody gets to decide. Next time I'm about to open an issue, I will consult with you first about the budget and whether the file to be translated is good to go. Thank you.

**Comment by ICA3DaR5** [comment]
The [PR](https://github.com/rchain/legaldocs/pull/2) is still open.

**Comment by ICA3DaR5** [comment]
Since this has already been paid on March, I am zeroing the month of May. Waiting for the PR to merge.
