### ISSUE TITLE
Translate the /reference/docs/RChainWhitepaper.pdf to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#496]
# Issue

## Original (English) Content
- [RChainWhitepaper.pdf](https://github.com/rchain/reference/blob/master/docs/RChainWhitepaper.pdf)

## Translated (Greek) Content
- []()

## Tasks
- [x] Download the original (English) file.
- [x] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Greek.
- [ ] Upload the translated file.

## Collaborators
- @ICA3DaR5: 40%
- @thiefinshadows: 15%
- @zero-andreou: 15%

## Other Information
- **Completed:** 70%
- **Suggested Budget:** $4000

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [x] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Greek community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Greek.
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: Diploma.
    - [x] A track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447 .

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by ian-bloom** [comment]
The Whitepaper is outdated.

More generally, there is not an easy path for discovery of non-English versions of RChain documents. The main links to the whitepaper are https://developer.rchain.coop/faq and https://github.com/rchain/reference/blob/master/faq.md

Why Greek? [At least 51% of Greeks speak English](http://greece.greekreporter.com/2014/06/12/half-of-the-greeks-speak-english/). What are the criteria for choosing content to translate and into which languages (translation strategy)?

**Comment by ICA3DaR5** [comment]
@ian-bloom I didn't know it was outdated.

I am sure 51% of Greeks speak English, albeit not very good English.

I'll close this.
