### ISSUE TITLE
Translate the rholang-spec-0.2.pdf to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#497]
# Issue

## Original (English) Content
- [rholang-spec-0.2.pdf](https://developer.rchain.coop/rholang-spec-0.2.pdf)

## Translated (Greek) Content
- [rholang-spec-0.2_GR.pdf](https://drive.google.com/open?id=1hpBSJ3UiqQiwxiYINVa3vWrotA9XYQVW)

## Tasks
- [x] Download the original (English) file.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have it reviewed by others with knowledge of English and Greek.
- [x] Upload the PDF file to [Google Drive](https://drive.google.com/drive/folders/0BwX0krsxHncTUjNKUnZuOVZGLWc).

## Collaborators
- @ICA3DaR5: 40%
- @thiefinshadows: 30%
- @zero-andreou: 30%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $2500

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [ ] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Greek developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Greek.
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: Diploma.
    - [x] A track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #540, #472 .

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by ICA3DaR5** [comment]
This is done!
