### ISSUE TITLE
M> Translate Architecture-docs/*.rst files to Russian

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#498]
**Completed:** 100%

**Tasks:**
- [x] Create the .rst files
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Russian
- [x] Create a [Pull Request](https://github.com/rchain/architecture-docs/pull/19)

**Collaborators Work:**
- @qelentium: 90%
- @pavlos1851: 5%
- @thiefinshadows :5%
- Why this document?
    - [x] It's important to translate because it will help russian developers community understand RChain
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [ ] at least two of them have high proficiency in Russian
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake;Diploma source: native russian speaker with Diploma
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: 30,03.2018

**Suggested Budget:** $5000

**Comment by dckc** [comment]
Hi. Russian is an important target according to our analytics (#454) and the architecture document is of course important.

Please point us to your work in progress.

Until you have at least shared your work-in-progress, I don't think you should claim the full $5000 in the budget voting system. I'm voting for a lower budget

**Comment by dckc** [comment]
@qelentium your github profile says almost nothing about you. Please share a little bit about yourself with us; in particular, your credentials for translating technical documentation.

See "significant reputation (e.g. a diploma)" in [ISSUE_TEMPLATE](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md).

**Comment by Jake-Gillberg** [comment]
Not sure that architecture docs are a good target for translation, given the recent conversation in #development on discord

**Comment by qelentium** [comment]
@dckc im a native russian speaker,ended russian school in europe, well know technical terminology of cryptoworld, started to learn python someday but never did it :))))

**Comment by dckc** [comment]
Ah... I can see the work now: https://github.com/rchain/architecture-docs/pull/17 
24217c6

@Jake-Gillberg if the organization wants to deprecate the architecture document, it should remove links from the home page, FAQ, etc.; until then, it seems like a pretty important document.

**Comment by ian-bloom** [comment]
@qelentium wrote:
>  ☑ It's on https://developer.rchain.coop/ that has been endorsed
for translation by @Jake-Gillberg, @MParlikar, or @KellyatPyrofex

I do not see an endorsement by any of these three. Can you provide a link showing that they have approved this work?

**Comment by qelentium** [comment]
We spoke with @Jake-Gillberg at Discord, and he said that we opened issues before the system changes and the work was done, so following instruction i uploaded.

**Comment by dckc** [comment]
This isn't done until [the pull request][19] is merged, is it?

[19]: https://github.com/rchain/architecture-docs/pull/19

**Comment by qelentium** [comment]
@dckc yeah,my fault

**Comment by ICA3DaR5** [comment]
Please create another PR for this, since your final work is not merged and previous PR was closed.

**Comment by qelentium** [comment]
Reopened PR

**Comment by ICA3DaR5** [comment]
@qelentium Awesome!

**Comment by ICA3DaR5** [comment]
This has already been paid in March, waiting for the PR to merge. I am zeroing this out for May.

**Comment by AyAyRon-P** [comment]
Has the PR happened? I'm closing this out since there has been no update in almost 30 days and payment was already delivered in March.
