### ISSUE TITLE
M> Translate /Rchain/Rholang/Doc/* to Russian

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#499]
**Completed:** 100%
https://github.com/rchain/rchain/blob/master/rholang/doc/rholangtut-0.1.md
https://github.com/rchain/rchain/blob/master/rholang/doc/rholangtut-mercury.md

**Tasks:**
- [x] Create the file
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Russian
- [x] Create a Pull Request

**Collaborators Work:**
- @qelentium: 90%
- @pavlos1851 : 5%
- @thiefinshadows  : 5%
  - Why this document? (mark all that apply)
    - [x] it's one of the /rchain/reference documents
    - [ ] I contacted the author, who agreed it's important to translate
    - [x] I know a person or audience who would benefit from it: The Russian community.
    - [ ] other: ___
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in Russian
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma.
       - [ ] a track record of quality work on rchain bounties:
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: 25.03.2018

**Suggested Budget:** $2300

**Comment by Jake-Gillberg** [comment]
Please put a link to the actual document or documents you wish to translate in the issue. Also, please make sure that your issue includes the [issue template](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md ). If this refers to [https://github.com/rchain/rchain/tree/master/rholang/doc](https://github.com/rchain/rchain/tree/master/rholang/doc), it is featured on [https://developer.rchain.coop/tutorial](https://developer.rchain.coop/tutorial), and I believe it is a good candidate for translation.

**Comment by qelentium** [comment]
I have done pull request 2 months ago but it was denied and i can't find it anywhere right now

**Comment by ICA3DaR5** [comment]
@qelentium Could you please re-open that PR. It needs to be merged for this issue to close.

**Comment by qelentium** [comment]
Reopened

**Comment by qelentium** [comment]
That's what KellAtPyrofex said about it: "This translation is for a now outdated version of the Rholang tutorial. Please close. The current tutorial is rholangtut-0.2.md (https://github.com/rchain/rchain/blob/master/rholang/doc/rholangtut-0.2.md). Most of the work here can be applied to that, and a new PR opened for review"

**Comment by ICA3DaR5** [comment]
@KellyatPyrofex Okay, so I would expect @qelentium to upload the newest version translated, since he has already been paid for this one. I am leaving this open until then.

**Comment by ICA3DaR5** [comment]
Since this has already been payed, I am putting a 0 budget for May, and expecting a PR of the newest version of the translated file.

**Comment by AyAyRon-P** [comment]
@qelentium has the PR happened? There has been no update in almost 30 days and payment was already delivered in March. 

cc @pavlos1851

**Comment by dckc** [comment]
rewarded in 201803
