### ISSUE TITLE
Translate the rholang-spec-0.2.pdf to Italian. 

### ISSUE THREAD

**Issue by akhs13** [rchain/bounties#502]
# Issue

## Original (English) Content
- [rholang-spec-0.2.pdf](https://developer.rchain.coop/rholang-spec-0.2.pdf)

## Translated (Italian) Content
- [rholang-spec-0.2_IT.pdf](https://drive.google.com/open?id=1IS3LrFo_tegE0jbWPjsLuHexPXWQn85B)

## Tasks
- [x] Download the original (English) file.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Italian. 
- [x] Upload it [here](https://drive.google.com/drive/folders/0BwX0krsxHncTUjNKUnZuOVZGLWc).

## Collaborators
- @akhs13: 40%
- @Chris-Arv : 30%
- #@panos1980: 30%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $3200

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [ ] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Italian developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Italian. 
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: Diploma.
    - [x] A track record of quality work on rchain bounties: #368, #367, #369, #392 

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by akhs13** [comment]
Finish.

**Comment by Staff91** [comment]
Update document.

**Comment by Staff91** [comment]
Update the [rholang-spec-0.2_IT.pdf](https://drive.google.com/open?id=1ynpGXMlKnDPmhuQ6Vuyi49s8D_AnmEO2)
