### ISSUE TITLE
M> Translate /Rchain/Rholang/Doc/* to Polish

### ISSUE THREAD

**Issue by jkost401** [rchain/bounties#517]
**Completed:** 100%

**Tasks:**
- [x] Create the files
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Polish.
- [x] Create a [Pull Request](https://github.com/rchain/rchain/pull/522)

**Collaborators Work:**
- @jkost401: 50%
- @pavlos1851  : 45%
- @qelentium  : 5%

**Suggested Budget:** $1900

  - Why this document?
    - It's important to translate because it's a documentation on Rholang.
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma.
       - [ ] a track record of quality work on rchain bounties:
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: keep it update.

**Comment by pavlos1851** [comment]
@Jake-Gillberg @MParlikar @kellyatPyrofex Should we translate this? Because the previous one got canceled and we already had started working on it.

**Comment by Jake-Gillberg** [comment]
@pavlos1851 At a quick glance, yes, this seems like a good target

**Comment by pavlos1851** [comment]
Great, please keep us posted on which files are to be translated and which are not.

**Comment by lapin7** [comment]
Maybe have a look at #347

**Comment by pavlos1851** [comment]
I've reopened the issue in order to upload the 0.2 version of the tutorial as well.

**Comment by Jake-Gillberg** [comment]
oops

**Comment by ICA3DaR5** [comment]
@pavlos1851 @jkost401 Is this abandoned? Since the PR is not merged and you wrote that you are going to open another issue for the new version?

**Comment by pavlos1851** [comment]
@ICA3DaR5 it is not abandoned. A new pull request will be created with the updated version of the document.

**Comment by AyAyRon-P** [comment]
@pavlos1851 @jkost401 @irynapopova61  what is the status of this issue? Has the PR happened? There has been no update in almost 30 days. 

**Please complete the task and close the issue.**

**Comment by Viraculous** [comment]
@jkost401 whats the progress of this issue?
