### ISSUE TITLE
Translate the rholang-spec-0.2.pdf to Polish.

### ISSUE THREAD

**Issue by pavlos1851** [rchain/bounties#527]
# Issue

## Original (English) Content
- [rholang-spec-0.2.pdf](https://developer.rchain.coop/rholang-spec-0.2.pdf)

## Translated (Polish) Content
- [rholang-spec-0.2_PL.pdf](https://drive.google.com/open?id=17PTq09WBjJIPR8H-QlgSR9UsuFCb309u)

## Tasks
- [x] Download the original (English) file.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Polish. 
- [x] Upload it [here](https://drive.google.com/drive/folders/0BwX0krsxHncTUjNKUnZuOVZGLWc).

## Collaborators
- @pavlos1851: 50%
- @jkost401  : 45%
- @qelentium : 5%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** 3000$

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [ ] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Polish developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Polish. 
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: Diploma.
    - [ ] A track record of quality work on rchain bounties:
- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by pavlos1851** [comment]
Complete.
