### ISSUE TITLE
Translate the rholang-spec-0.2.pdf to Russian

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#528]
# Issue

## Original (English) Content
- [rholang-spec-0.2.pdf](https://developer.rchain.coop/rholang-spec-0.2.pdf)

## Translated (Russian) Content
- [rholang-spec-0.2-RU.pdf](https://drive.google.com/open?id=1nVQsvn8wfOHLCD3brTUUavrqD4X6eJGw)

## Tasks
- [x] Download the original (English) file.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Russian. 
- [x] Upload it [here](https://drive.google.com/drive/folders/0BwX0krsxHncTUjNKUnZuOVZGLWc).

## Collaborators
- @qelentium: 90%
- @pavlos1851   :5%
- @thiefinshadows  : 5%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $4000

---

- Why this/these document(s)? (mark all that apply)
  - [ ] It's one/some of the /rchain/reference document(s).
  - [x]  It's on https://developer.rchain.coop/ that has been endorsed for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: Russian developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Russian. 
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: Diploma.
    - [ ] A track record of quality work on rchain bounties:
- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is:31.03.2018.

**Comment by qelentium** [comment]
@Jake-Gillberg
