### ISSUE TITLE
Translate rchain/architecture-docs/* to Ukrainian

### ISSUE THREAD

**Issue by irynapopova61** [rchain/bounties#530]
# Issue

## Original (English) Content
- [rchain/architecture-docs/*](https://github.com/rchain/architecture-docs)

## Translated (Ukrainian) Content
- []()

## Tasks
- [x] Download the original (English) files.
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Ukrainian.
- [ ] Create a Pull Request.

## Collaborators
- @irynapopova61: 10%
- @thiefinshadows: 0%
- @: 0%

## Other Information
- **Completed:** 10%
- **Suggested Budget:** $3200

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [ ] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Greek developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Ukrainian.
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: Diploma.
    - [ ] A track record of quality work on rchain bounties: 

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.
