### ISSUE TITLE
Translate the rholang-spec-0.2.pdf to Ukrainian

### ISSUE THREAD

**Issue by irynapopova61** [rchain/bounties#531]
# Issue

## Original (English) Content
- [rholang-spec-0.2.pdf](https://developer.rchain.coop/rholang-spec-0.2.pdf)

## Translated (Ukrainian) Content
- [rholang-spec-0.2_UK.pdf](https://drive.google.com/open?id=1B6uc-rZP7yiVloIz717xWakosMEnWb6R)

## Tasks
- [x] Download the original (English) file.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Ukrainian. 
- [x] Upload it [here](https://drive.google.com/drive/folders/0BwX0krsxHncTUjNKUnZuOVZGLWc).

## Collaborator
- @irynapopova61: (translator) 60%
- @thiefinshadows  : (translator) 35%
- @qelentium (reviewer)  5%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $3500

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [ ] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Ukrainian developers community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Ukrainian. 
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: Diploma.
    - [ ] A track record of quality work on rchain bounties:

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by lapin7** [comment]
@irynapopova61 please send your email address to ops@rchain.coop

**Comment by irynapopova61** [comment]
@Jake-Gillberg can i translate that 3 issues ?

**Comment by Jake-Gillberg** [comment]
@irynapopova61 which 3? This one seems like a good target for translation, though I am unsure of your suggested budget.

**Comment by thiefinshadows** [comment]
Finish.
