### ISSUE TITLE
M> Translate /Rchain/Rholang/Doc/* to Ukrainian

### ISSUE THREAD

**Issue by irynapopova61** [rchain/bounties#532]
**Completed:** 100%

**Tasks:**
- [x] Download the files
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Ukrainian
- [x] Create a [Pull Request](https://github.com/rchain/rchain/pull/517)

**Collaborators Work:**
- @irynapopova61: (translator) 60%
- @thiefinshadows  :(translator) 35%
- @qelentium  (reviewer) 5%

**Suggested Budget:** $2300

**Comment by thiefinshadows** [comment]
Finish.

**Comment by ICA3DaR5** [comment]
This issue is invalid because the PR was not accepted. I am expecting @thiefinshadows to create a new issue and upload the newest version.

**Comment by dckc** [comment]
The $2300 reward was paid out in March. Perhaps it's better to do the remaining work under this issue to be sure we don't pay for it again?
