### ISSUE TITLE
Translate the /rchain/reference/*.md files to Ukrainian

### ISSUE THREAD

**Issue by irynapopova61** [rchain/bounties#533]
# Issue

## Original (English) Content
- [rchain-reference/*.md](https://github.com/rchain/reference)

## Translated (Ukrainian) Content
- []()

## Tasks
- [x] Download the original (English) files.
- [x] Translate the content.
- [x] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Ukrainian.
- [ ] Upload the translated files.

## Collaborators
- @irynapopo61  (Translator): 60%
- @thiefinshadows  (Translator): 20%
- @jkost401  (reviewer)  0%

## Other Information
- **Completed:**80%
- **Suggested Budget:** $2000

---

# Translators Q&A

- Why this/these document(s)? (mark all that apply)
  - [x] It's one/some of the /rchain/reference document(s).
  - [ ] I contacted the author, who agreed it's important to translate.
  - [x] I know a person or audience who would benefit from it: The Ukrainian community.
  - [ ] Other: ...

- How can people who do not speak this language be assured of the quality of the translation? (all are required) 
  - [x] Several reviewers are involved. (assign the ticket to them)
  - [x] At least two of them have high proficiency in English.
  - [x] At least two of them have high proficiency in Ukrainian.
  - [x] At least two of them have either:
    - [x] Significant reputation (e.g. a diploma) at stake; source: diploma
    - [x] A track record of quality work on rchain bounties: 

- What about maintenance? (choose one)
  - [ ] The source document(s) is/are stable; further translation work is not expected.
  - [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by irynapopova61** [comment]
Good morning should i continue translating that issue ?
