### ISSUE TITLE
Translate the Medium blog posts to Italian

### ISSUE THREAD

**Issue by akhs13** [rchain/bounties#537]
**Completed:** 100%

**Tasks:**
- [x] Copy the posts to text files.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Italian.
- [x] Post them to the Italian [Medium](https://medium.com/@rchain_it) account.

**Collaborators Work:**
- @akhs13: 40%
- @Chris-Arv : 30%
- @panos1980 : 30%

**Suggested Budget:** $1400

# Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved
    - [x] at least two of them have high proficiency in Italian
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #368, #367, #369, #392
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____
