### ISSUE TITLE
Translate the "RChain node version 0.1.3 released" blog post to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#540]
# Issue

## Original (English) Content
- [RChain node version 0.1.3 released](https://medium.com/rchain-cooperative/rchain-node-version-0-1-3-released-ede6cb2d57f7)

## Translated (Greek) Content
- [Η έκδοση RChain κόμβου 0.1.3 κυκλοφόρησε](https://medium.com/@rchain.gr/%CE%B7-%CE%AD%CE%BA%CE%B4%CE%BF%CF%83%CE%B7-rchain-%CE%BA%CF%8C%CE%BC%CE%B2%CE%BF%CF%85-0-1-3-%CE%BA%CF%85%CE%BA%CE%BB%CE%BF%CF%86%CF%8C%CF%81%CE%B7%CF%83%CE%B5-e5468baf6210)

## Tasks
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have it reviewed by others with knowledge of English and Greek.
- [x] Post it to the [Greek Medium account](https://medium.com/@rchain.gr).
- [x] Post it to the Greek [VK](https://vk.com/rchain_gr), [Facebook](), [Twitter](https://twitter.com/rchain_gr) and [Telegram](https://t.me/rchain_gr) accounts.

## Collaborators
- @ICA3DaR5: 40%
- @thiefinshadows: 30%
- @zero-andreou: 30%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $116.67

---

# Translators

  - Why this document?
    - It's important to translate because
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved
    - [x] at least two of them have high proficiency in Greek
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma.
       - [ ] a track record of quality work on rchain bounties:  #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475 .
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____
