### ISSUE TITLE
Translate the rholang-spec-0.2.pdf to Croatian

### ISSUE THREAD

**Issue by MarioPolo** [rchain/bounties#546]
#  Issue
----

## Original (English) Content

*  [ rholang-spec-0.2.pdf ]( https://developer.rchain.coop/rholang-spec-0.2.pdf)
## Translated (Croatian) Content

*  [ rholang-spec-0.2._HR.pdf ](https://drive.google.com/file/d/1RXpa0is_J7nTz5iF_ICaed4XgEmY2YUL/view?usp=sharing)
## Tasks

 *   [x]   Download the original (English) file.
 *   [x]   Translate the content.
 *   [x]   Check the spelling.
  *   [x]  Review each other's work.
 *   [x]   Have them reviewed by others with knowledge of English and Croatian.
  *   [x]  Upload it here.

## Collaborators

  * @MarioPolo : 40%
  * @InternautNeven : 30%
  * @Howsoonisnow  : 30%

## Other Information

  * Completed: 100%
  * Suggested Budget: $2500

# Translators Q&A

 * Why this/these document(s)? (mark all that apply)

     *   [ ]   It's one/some of the /rchain/reference document(s).
     *   [ ]   I contacted the author, who agreed it's important to translate.
     *  [x] I know a person or audience who would benefit from it: The Croatian developers community.  
     *  [ ] Other: ...
----
* How can people who do not speak this language be assured of the quality of the translation? (all are required)

    *   [ ]   Several reviewers are involved. (assign the ticket to them)
    *   [x]   At least two of them have high proficiency in English.
    *   [x]   At least two of them have high proficiency in Croatian.
    *   [x]   At least two of them have either:
          *   [x]   Significant reputation - InternautNeven: (MS) IT Management, Howsoonisnow: (MS) Professor 
          *   [x]   A track record of quality work on rchain bounties: #382 #125 #449 
----
* What about maintenance? (choose one)

    *   [ ]   The source document(s) is/are stable; further translation work is not expected.
    *   [x]   Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by BelovedAquila** [comment]
@MarioPolo nice one friend, I suppose  you didn't observe your collaborators percentage was above 100%?

**Comment by MarioPolo** [comment]
@BelovedAquila you did notice well, that was wrong. It's okay now, thanks

**Comment by jplepel** [comment]
Voted in the new bounty app for a $0 budget. 

Reason: According to wikipedia most Croatians know Itialian, and English is commonly known by the younger generation. We already have an Italian translation. 

I will gladly change my vote if convinced otherwise. Personally have never seen a new user come into the discord or telegram channels speaking Croatian. If there is a large market for non-english speaking Croatians with interest in Rchain, please direct me towards that crowd.

**Comment by BelovedAquila** [comment]
@jplepel was wondering if they can just be given a benefit of doubt for this work, after which they won't have to be working on further Croatian translations, that's depending on how far they have gone with the work, at least their time and attempt to contribute to the expansion of the coop merits being rewarded, don't you see that?

**Comment by MarioPolo** [comment]
We are not the first that translate in this language first was @lapin7 and Issue #262. 
Same language is spoken also in Serbia, Montenegro and Bosnia and with diferent levels of understanding in Slovenia and Macedonia so in total more than 20 milions of people and minimum of 15 milions of people abroad. 
As for Italian it is understandable only in some parts of country but it is not more than 5 percent of total population.
Actualy Italian minority in Croatia, is only 0.43% also english is commonly undersandable by around 35 percent but with diferent levels of understanding and I belive that you would agree that this translation(Rholang) is very specific and requires specific areas of knowledge.

**Comment by jplepel** [comment]
@MarioPolo @BelovedAquila Thanks for the input. Do we have a number of downloads/views for previously translated documents in Croatian? Would like to confirm some demand for these translations. Can you also detail out how you got to a $3200 budget? 

Still getting familiar with the translation bounties, I believe we should start to be more frugal with the selection of documents and budget amounts.

**Comment by MarioPolo** [comment]
@jplepel @BelovedAquila Yes of course, we saw prices of others ( and lower it down- from like this one, few days ago: https://github.com/rchain/bounties/issues/528 ),

Please analyze text-  it is not the common english, it takes knowledge in programing 
and mathematics.
  Should our language be evaluated less than any other (for same effort and time invested) double less or with zero?

As for the demand we will organize Meetup 03.05.2018. #125 where we will distribute documents 
(probablly  once in month) and our plan is make a website- blog in near future,  with all this documents. 
I  dont think there is a easy way to validate someones work, it is something like predicting value of any blockchain on market, lets say in five years from now. 

I`m sure that someone in future will have some benefit from all this that we do, 
it takes time, but with constructive advices, sugestions,
I am sure that we will make it.

**Comment by BelovedAquila** [comment]
>Should our language be evaluated less than any other (for same effort and time invested) double less or with zero?
@jplepel @MarioPolo actually that would be a kind of unfair discrimination which isn't part of the good norms of the coop. 

>I don't  think there is a easy way to validate someone's  work, it is something like predicting value of any blockchain on market, lets say in five years from now.
Actually yes, although not withstanding, the fact that the little measures made on supervision is a welcomed development, but I still recommend, if not for anything, EQUITY when dealing with issues supervision, especially in a way it won't instigate discrimination, personal bias or injustice.
>I`m sure that someone in future will have some benefit from all this that we do,
it takes time, but with constructive advices, sugestions,
I am sure that we will make it.
Definitely, We don't tend to know what is ahead, we just make good paces to it believing by our good paces the outcome of tomorrow  would be positive.
Anyway to add to, I think there is a need for our attendance and contributions on today's meeting#575  to still air our opinions  for a better standing

**Comment by MarioPolo** [comment]
It's finished!
