### ISSUE TITLE
M> Translate rchain/rholang/doc/rholangtut-0.2.md to Italian

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#574]
**Completed:** 100%

**Tasks:**
- [x] Create the file []()
- [x] Translate the content
- [x] Check the spelling
- [x] Review each other's work
- [x] Have it reviewed by others with knowledge of English and Italian
- [x] [Create a Pull Request](https://github.com/rchain/rchain/pull/566)

**Collaborators Work:**
- @Staff91: 40%
- @akhs13 : 30%
- @Chris-Arv : 30%

**Suggested Budget:** $450

2300+- words.

Thanks for your interest in telling the story of RChain in another language.

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [ ] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #367 #368 #369 #392 #488 #489 #502 #537 
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by Staff91** [comment]
Finish.
