### ISSUE TITLE
M> Translate bounties/README.md and bounties/CONTRIBUTING.md

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#577]
**Completed:** 100%

**Tasks:**
- [ ] Create the file []()
- [ ] Create the file []()
- [ ] Translate the content
- [ ] Check the spelling
- [ ] Review each other's work
- [ ] Have it reviewed by others with knowledge of English and Italian
- [ ] Create a [Pull Request](https://github.com/rchain/bounties/pull/600)

**Collaborators Work:**
- @Staff91: 40%
- @akhs13 : 30%
- @Chris-Arv : 30%

**Suggested Budget:** $250

1200+- words.

Thanks for your interest in telling the story of RChain in another language.

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [ ] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #367 #368 #369 #392 #488 #489 #502 #537 
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by Jake-Gillberg** [comment]
> Why this document?

Please fill out this section. A group consensus is the two reasons that a document would be good for translation are:
> It's an RChain blog item
> It's on https://developer.rchain.coop/ that has been endorsed
for translation by @Jake-Gillberg, @MParlikar, or @KellyatPyrofex

If neither of those things are true, you should be justifying the reason for translation and making sure that others are on board, so you are dissatisfied with $0 bounty votes at the end of the month.

**Comment by Staff91** [comment]
"Why this document?"
Because I want to add it to the Italian website. If that's not okay, tell me, and I will close the issue.

**Comment by Jake-Gillberg** [comment]
What Italian website? The one discussed in #569? It looks like it doesn't exist yet, or that you may be doing it "rouge" then bringing it back to the group when you have measurements?

> I will make the website irregardless, we will find a way for you to be able to be able to measure the results of my work. If the results are promising, then good for everybody, if not, then it's my loss :) I will open a new issue and we will discuss the specifics over there.

In any case, I'm not sure that these documents have relevancy on website outside of this github repo.

**Comment by Staff91** [comment]
ok. I understand

**Comment by Staff91** [comment]
Finish!
