### ISSUE TITLE
Translate two new blog posts to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#585]
# Issue

## Original (English) Content
- [RNode-0.2.1 integrates Rholang to the RChain Node](https://medium.com/rchain-cooperative/rnode-0-2-1-integrates-rholang-to-the-rchain-node-183c0e13b024?source=collection_home---6------1----------------)
- [Introducing RSpace](https://medium.com/rchain-cooperative/introducing-rspace-ea12897daef2?source=collection_home---6------0----------------)

## Translated (Greek) Content
- [Το RNode-0.2.1 ενσωματώνει την Rholang στον Κόμβο RChain](https://medium.com/@rchain.gr/%CF%84%CE%BF-rnode-0-2-1-%CE%B5%CE%BD%CF%83%CF%89%CE%BC%CE%B1%CF%84%CF%8E%CE%BD%CE%B5%CE%B9-%CF%84%CE%B7%CE%BD-rholang-%CF%83%CF%84%CE%BF%CE%BD-%CE%BA%CF%8C%CE%BC%CE%B2%CE%BF-rchain-aafbe106ae02?source=user_profile---------1----------------)
- [Εισαγωγή στο RSpace](https://medium.com/@rchain.gr/%CE%B5%CE%B9%CF%83%CE%B1%CE%B3%CF%89%CE%B3%CE%AE-%CF%83%CF%84%CE%BF-rspace-5e9f9d3baf91)

## Tasks
- [x] Copy the original (English) content to the [RChain Cooperative — Greek](https://medium.com/@rchain.gr) Medium blog.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Greek.
- [x] Post the translated (Greek) content to the [RChain Cooperative — Greek](https://medium.com/@rchain.gr) Medium blog.

## Collaborators
- @ICA3DaR5: 50%
- @zero-andreou: 50%
- @thiefinshadows: 0%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $400

---

# Translators

Thanks for your interest in telling the story of RChain in another language.

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #540, #472, #497 .
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____
