### ISSUE TITLE
Translate rchain/rholang/doc/rholangtut-0.2.md to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#586]
# Issue

## Original (English) Content
- [rholangtut-0.2.md](https://github.com/rchain/rchain/blob/master/rholang/doc/rholangtut-0.2.md)

## Translated (Greek) Content
- [rholangtut-0.2_GR.md](https://github.com/rchain/rchain/blob/master/rholang/doc/rholangtut-0.2_GR.md)

## Tasks
- [x] Download the original (English) content.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have it reviewed by others with knowledge of English and Greek.
- [x] Create a [Pull Request](https://github.com/rchain/rchain/pull/574).

## Collaborators
- @ICA3DaR5: 50%
- @zero-andreou: 50%
- @thiefinshadows: 0%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $500

---

# Translators

Thanks for your interest in telling the story of RChain in another language.

  - Why this document?
    - [x] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved
    - [x] at least two of them have high proficiency in Greek
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Proficiency in English from the University of Michigan, Lower in English from the University of Cambridge and Proficiency in English from Edexcel.
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #540, #472, #497, #585, #597, #621 
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected

**Comment by ICA3DaR5** [comment]
We'll upload the translated version of rholangtut-0.3.md soon.
