### ISSUE TITLE
Translate two new blog posts to Italian

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#587]
# Issue

## Original (Italian) Content
- [RNode-0.2.1 integrates Rholang to the RChain Node](https://medium.com/rchain-cooperative/rnode-0-2-1-integrates-rholang-to-the-rchain-node-183c0e13b024?source=collection_home---6------1----------------)
- [Introducing RSpace](https://medium.com/rchain-cooperative/introducing-rspace-ea12897daef2?source=collection_home---6------0----------------)

## Translated (Italian) Content
- []()
- []()

## Tasks
- [ ] Copy the original (English) content to the [RChain Cooperative — Italian](https://medium.com/@rchain_it) Medium blog.
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Italian.
- [ ] Post the translated (Italian) content to the [RChain Cooperative — Italian](https://medium.com/@rchain_it) Medium blog.

## Collaborators
- @Staff91: 0%
- @akhs13 : 0%
- @Chris-Arv : 0%

## Other Information
- **Completed:** 0%
- **Suggested Budget:** $450

---

# Translators

Thanks for your interest in telling the story of RChain in another language.

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties:  #367 #368 #369 #392 #488 #489 #502 #537  .
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____
