### ISSUE TITLE
M>Translation of the "RChain Vision" video to Italian 

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#590]
# All

The RChain Vision video: https://youtu.be/Qftq9S34xgg

**Completed:** 0%

**Tasks:**
- [x] Download the video
- [ ] Create an Italian transcript
- [ ] Check the spelling
- [ ] Review each other's work
- [ ] View video with the Italian transcript and review
- [ ] Have the Italian transcript reviewed by others with knowledge of Italian
- [ ] Upload the Italian (translated) transcript, [here]()
- [ ] Upload the Italian subtitles to the [original video]()

**Collaborators Work:**
- @Staff91: 0%
- @akhs13 : 0%
- @Chris-Arv : 0%

**Suggested Budget**: $150

Italian Transcript .srt File: 

Thanks for your interest in telling the story of RChain in another language.

   - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [ ] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #367 #368 #369 #392 #488 #489 #502 #537 
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____
------------------------------------------------------------------------------------------------------------------
   - [x] It's for the Italian website
