### ISSUE TITLE
Translate Medium Blog Posts to Spanish

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#597]
# Issue

## Original (English) Content
- [RChain Cooperative Medium](https://medium.com/rchain-cooperative)

## Translated (Spanish) Content
- [RChain Cooperative (Spain) Medium](https://medium.com/@rchain_es)

## Tasks
- [x] Copy the original (English) content to the [RChain Cooperative (Spain)](https://medium.com/@rchain_es) Medium blog.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Spanish.
- [x] Post the translated (Spanish) content to the [RChain Cooperative (Spain)](https://medium.com/@rchain_es) Medium blog.

## Collaborators
- @ICA3DaR5: 40%
- @zero-andreou: 40%
- @michaelizer : 20%

## Other Information
- **Completed:** 100%
- **Suggested Budget:** $3200

---

# Translators

  - Why this document?
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #540, #472, #497, #585 .
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected

**Comment by kitblake** [comment]
Do we have native Spanish speakers doing the translation? 
I don't see any Spanish-looking names assigned.

**Comment by kitblake** [comment]
Thanks. Spanish looks to be important. Right now it's #4 in the poll: 
Chinese, Russian, Japanese, Spanish....

**Comment by dckc** [comment]
The title looked like "translate any medium blog post...".

Regarding diplomas.... where are they from? Are they relevant to Spanish?
I have a Computer Science diploma from the University of Texas at Austin, but that in no way qualifies me to do Spanish translation.

**Comment by zero-andreou** [comment]
We both have a DELE C1 from the Cervantes Institute. It's been a few years since we got them so perhaps our spanish may be a bit rusty,  but we feel confident that we can deliver. Since spanish comes second in ranking languages by number of native speakers and nobody has translated anything yet we thought we'd give it a go.

**Comment by dckc** [comment]
OK, such a diploma looks quite relevant. Your plan to include a native Spanish speaker looks workable.

**Comment by jasoncruzzy** [comment]
@ICA3DaR5 i think the diploma qualification is ok. only a few corrections will be made by the reviewer....Another good idea to expand the base of #Rchain

**Comment by ICA3DaR5** [comment]
@michaelizer Hello, I noticed that you are based in Venezuela. Is your native language Spanish?

If so, would you like to be a reviewer on this issue? Also, could you please share your Discord username, so we can PM?

Thanks a lot!

**Comment by michaelizer** [comment]
@ICA3DaR5 yes, it is.

michaelizer#2321, PM me :))

**Comment by ICA3DaR5** [comment]
@michaelizer Can you PM me because I can't find you?

Discord: ICA3DaR5#1090
