### ISSUE TITLE
Translate all (12) Medium blog posts to Ukrainian

### ISSUE THREAD

**Issue by irynapopova61** [rchain/bounties#599]
**Completed:** 100%

**Tasks:**
- [x] Copy the posts to text files.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Ukrainia.
- [x] Post them to the Ukranian [Medium](https://medium.com/@rchain_ukraine) account.

Collaborators Work:

- @irynapopova61
- @thiefinshadows 
- @jkost401 

**Suggested Budget:** $2600
 

  # Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved
    - [x] at least two of them have high proficiency in Ukrainian
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #531 #532 
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by Pionelle** [comment]
@irynapopova61 Hello, Здрастуйте, сторінка, перерахована тут, повернула нездатність підключитися, оскільки місцезнаходження не знайдено. Будь-ласка, перевірте, чи підтверджуєте офіційну сторінку засобу масової інформації "Регіональні україни"

**Comment by Pionelle** [comment]
A Bug in this is the Medium page is not found. Maybe network. This is needing of a resolution so many Ukranian members can access these translated works>
