### ISSUE TITLE
Translate all (12) Medium blog posts to Polish

### ISSUE THREAD

**Issue by pavlos1851** [rchain/bounties#612]
**Tasks:**
- [x] Copy the posts to text files.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Polish.
- [x] Post them to the Polish [Medium](https://medium.com/@rchain_pl) account.

*Estimated Budget of Task:* **$[2000]**  \
*Estimated Timeline Required to Complete the Task:* **[8 days]**  \
*Measure of Completion:* **[100%]**

### For Translators
@pavlos1851
@jkost401 
@irynapopova61 

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in Polish.
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #527 #517
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by dckc** [comment]
As we have just the one issue tagged "Polish" I think we can just find it by text search. Let's keep to a manageable number of labels.

**Comment by ICA3DaR5** [comment]
@pavlos1851 What's the status of this?

**Comment by pavlos1851** [comment]
@ICA3DaR5 Because of some unexpected personal issues, it's only halfway done. I expect it to be ready in a week or so.

**Comment by ICA3DaR5** [comment]
@pavlos1851 Awesome!

**Comment by ICA3DaR5** [comment]
Any progress on this?

**Comment by pavlos1851** [comment]
@ICA3DaR5 Hi. It is completed.
