### ISSUE TITLE
Translate "Resonate and lifeID collaborate" blog post to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#621]
# Issue

## Original (English) Content
- [Resonate and lifeID collaborate](https://medium.com/rchain-cooperative/resonate-and-lifeid-collaborate-da2d22e43df6)

## Translated (Greek) Content
- [Η Resonate και η lifeID συνεργάζονται](https://medium.com/@rchain.gr/%CE%B7-resonate-%CE%BA%CE%B1%CE%B9-%CE%B7-lifeid-%CF%83%CF%85%CE%BD%CE%B5%CF%81%CE%B3%CE%AC%CE%B6%CE%BF%CE%BD%CF%84%CE%B1%CE%B9-56c5093065d0)

## Tasks
- [x] Copy the original (English) content to the [RChain Cooperative — Greek](https://medium.com/@rchain.gr) Medium blog.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Greek.
- [x] Post the translated (Greek) content to the [RChain Cooperative — Greek](https://medium.com/@rchain.gr) Medium blog.

## Collaborators
- @ICA3DaR5: 50%
- @zero-andreou: 50%
- @thiefinshadows: 0%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$250**  \
*Estimated Timeline Required to Complete the Task:* **3 days**  \
*Measure of Completion:* **100%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #540, #472, #497, #585, #597 
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____
