### ISSUE TITLE
Translate RChain Cooperative (Medium) Blog Posts to German

### ISSUE THREAD

**Issue by gsofianidis** [rchain/bounties#633]
# Issue

## Original (English) Content
- [RChain Cooperative - Medium](https://medium.com/rchain-cooperative)

## Translated (German) Content
- [RChain Cooperative (German)](https://medium.com/@rchain_de)

## Tasks
- [x] Copy the original (English) content to the [RChain Cooperative (German)](https://medium.com/@rchain_de) Medium blog.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and German.
- [x] Post the translated (German) content to the [RChain Cooperative (German)](https://medium.com/@rchain_de) Medium blog.

## Collaborators
- @gsofianidis: 50%
- @amaliasof: 50%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$3200**  \
*Estimated Timeline Required to Complete the Task:* **3 days**  \
*Measure of Completion:* **100%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [ ] a track record of quality work on rchain bounties:
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by lapin7** [comment]
@gsofianidis 
To contribute to RChain:

- [ ] watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [ ] read RChain Decentralized Bounty Program https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [ ] Join RChain Coop by signing up for membership
- [ ] Join https://groups.google.com/forum/#!forum/rchain/join to get access to documents of RChain. rchain@googlegroups.com 
- [ ] fill out form RAM registration https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform
- [ ] Join github/rchain/bounties in order to contribute
- [ ] Claim your reward with form Declaration https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
