### ISSUE TITLE
Translate rholang-spec-0.2.pdf to Spanish

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#652]
# Issue

## Original (English) Content
- [rholang-spec-0.2.pdf](https://developer.rchain.coop/assets/rholang-spec-0.2.pdf)

## Translated (Spanish) Content
- [rholang-spec-0.2_ES.pdf](https://drive.google.com/open?id=1HQTjdPdmpVv-OEs0M4a7vCbkLu_l-cOg)

## Tasks
- [x] Download the original (English) content.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Spanish.
- [x] Upload the PDF file to [Google Drive](https://drive.google.com/open?id=1HQTjdPdmpVv-OEs0M4a7vCbkLu_l-cOg).

## Collaborators
- @ICA3DaR5: 40%
- @zero-andreou: 40%
- @michaelizer : 20%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$2500**  \
*Estimated Timeline Required to Complete the Task:* **28 days**  \
*Measure of Completion:* **100%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #540, #472, #497, #585, #597, #621, #586, #688, #650 
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by qelentium** [comment]
Can i see your diploma of knowledge of spanish?
