### ISSUE TITLE
Translate rholang-spec-0.2.pdf to French 

### ISSUE THREAD

**Issue by BelovedAquila** [rchain/bounties#653]
Issue

## Original (English) Content
- [rholang-spec-0.2-pdf](https://developer.rchain.coop/assets/rholang-spec-0.2.pdf)

## Translated (French) Content
- [rholang-spec-0.2_FR.pdf](https://docs.google.com/document/d/1aJiWTLPE23GvbiuFCN57bt_MmRWYEDxUQY2Lg0E9dRI/edit?usp=drivesdk)

## Tasks
- [x] Download the original (English) content.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and French.
- [x] Upload the PDF file to  Google drive [here](https://drive.google.com/drive/folders/0BwX0krsxHncTUjNKUnZuOVZGLWc).
## Collaborators
- @BelovedAquila 
- @Pionelle 
- @philipandri002 
---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$2000**  \
*Estimated Timeline Required to Complete the Task:* **10 days**  \
*Measure of Completion:* **100%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [ ] a track record of quality work on rchain bounties: #464 #623 #653
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____to

**Comment by Pionelle** [comment]
Bon travail fait jusqu'ici les gars!

**Comment by BelovedAquila** [comment]
Oui, Nous allons le télécharger sur le disque Google bientôt, 
Après le dernier revue

**Comment by truffard** [comment]
@BelovedAquila @Pionelle les filles, je n'ai toujours pas accés au document....

**Comment by BelovedAquila** [comment]
@truffard Vérifiez à nouveau s'il vous plaît

**Comment by truffard** [comment]
@BelovedAquila il y a beaucoup de corrections à faire, j'ai commencé... @Pionelle es tu la?

**Comment by dckc** [comment]
I see the whole $3000 budget was claimed, but I'm struggling to find the results from https://developer.rchain.coop/ or even https://github.com/rchain/rchain/tree/master/docs/rholang . Oh... the issue description says the target is gdrive. I don't see how that's valuable -- how does the audience find it? Translations should appear right next to the originals, no? And the target isn't even published (it wants me to ask for access).

This issue wasn't even posted until May 2. Why was the bounty claimed in the April pay period?

0.2 is already obsolete; I see an 0.3 in https://github.com/rchain/rchain/tree/master/docs/rholang . Did you coordinate with the authors? Do they want a French translation? (I suppose French scored reasonably high in the poll summarized Apr 17 by @kitblake in #483 ...)

cc @ICA3DaR5, @zero-andreou, @michaelizer,

**Comment by truffard** [comment]
@Pionelle @BelovedAquila @dckc I made so many corrections on the document ....They' re not reflected and none of the comments I made show up... Where are they?

**Comment by kitblake** [comment]
@BelovedAquila You deleted this comment from @truffard:

> @BelovedAquila il y a beaucoup de corrections à faire, j'ai commencé... @Pionelle es tu la?

Pourquoi ?

**Comment by truffard** [comment]
@kitblake @dckc apparently one can claim a bounty even if the job is incomplete.The document is a gibberish of french

**Comment by dckc** [comment]
@truffard as noted in #682, in collaboration with some others, I moved the votes on this issue to May so that the negotiation isn't rushed.

**Comment by truffard** [comment]
@dckc as you mentioned earlier 0.2 is obsolete. I unassigned myself from the issue

**Comment by ICA3DaR5** [comment]
@truffard @dckc Is there a rholang-spec-0.3 somewhere? Can't find it on the [developers](https://developer.rchain.coop/) website.

**Comment by dckc** [comment]
As I noted above, "I see an 0.3 in https://github.com/rchain/rchain/tree/master/docs/rholang . "

**Comment by BelovedAquila** [comment]
@kitblake and @dckc the first doc uploaded was messed up, so had to upload a fresh copy.
And I am reworking on the doc to make the corrections stated where necessary, after which it will still be reviewed. 
@truffard you have your special reasons for your exaggerated fallacious conclusion, which I am still going to consider . Thank you

**Comment by truffard** [comment]
@BelovedAquila i did help you for this document but you won't mention that, and according to @lapin7 one must be a native speaker in order to collaborate on a translation project

**Comment by dckc** [comment]
No, I don't think so.

**Comment by BelovedAquila** [comment]
@dckc that would make your presumption or judgment unstable or bias

**Comment by dckc** [comment]
> ... you can't actually ascertain that until the doc is completed so slashing the votes already is like placing judgments before considering evidences, don't you think so?

It's not complete by your own estimation and yet you claim 90% of a $3000 budget:

201805 | BelovedAquila | BelovedAquila: BelovedAquila | 90 |   | Tue May 8 11:21:59 2018
-- | -- | -- | -- | -- | --

That's plenty of evidence.

If you want me to withdraw my slashing vote, don't defend your clearly unfair position; change your votes and address the questions and criticism above.

**Comment by ICA3DaR5** [comment]
@BelovedAquila Google Drives won't do. You have to create a [Pull Request](https://help.github.com/articles/about-pull-requests/).

**Comment by BelovedAquila** [comment]
@dckc yes because we have to revisit the said errors and scrutinize the whole document again, more reasons why you ought not place judgment on the doc already, till its completed. And I don't see any question I haven't answered.

@ICA3DaR5 never mind, it would be resolved once we are done. Thank you

**Comment by BelovedAquila** [comment]
This issue is still valid, as there isn't any justified reason to it being slashed and even close when work is still ongoing on it

**Comment by ICA3DaR5** [comment]
Alright, keep it open.

**Comment by BelovedAquila** [comment]
The Reviewed document of this issue has just been uploaded and its open to criticism and further independent reviews.

**Comment by dckc** [comment]
No more than I already said.

**Comment by BelovedAquila** [comment]
@dckc what else haven't been addressed here please? Why does it seem like you are shying away from pointing out? You don't judge something you know nothing about that way,I know my efforts on this issue and am willing to defend it, so make your point.

**Comment by ICA3DaR5** [comment]
If you want me to withdraw my slashing vote, don't defend your clearly unfair position; change your votes and address the questions and criticism above.

**Comment by BelovedAquila** [comment]
Ok, thank you @ICA3DaR5 what is yet to be done is  changing my vote,which aspects of the vote needed to be changed and to what? am open to fair suggestions please @dckc @kitblake

**Comment by allancto** [comment]
@BelovedAquila thanks for your comments. My understanding is that there was a translation done which was assessed by @truffard @ICA3DaR5 and @dckc as not an adequate within our ability to measure, and will not be eligible for reward. I'm not an expert in French translation, but @ICA3DaR5 is trusted by me and by the voting system to make this determination. 

Are there other issues you might be interested in participating in?

**Comment by BelovedAquila** [comment]
@allancto thank you very much, I will not want to raise more issues on this, but I will have my doc on this issue reviewed by other French collaborators on the basis of an independent review, @truffard alone  isn't sufficient to determine the adequacy of the translated doc on this issue, @ICA3DaR5 and @dckc aren't French fluent either, so please I would have it reviewed by an independent reviewer so as to ascertain how true the propositions are please.

**Comment by truffard** [comment]
@BelovedAquila you say I alone am not enough to determine the adequacy of the translated doc. I think I'm sufficient to assess your insufficient level of French.

**Comment by Jake-Gillberg** [comment]
This document is now out of date

**Comment by Pionelle** [comment]
@truffard There are francophone countries apart from in Europe. Where the language is the first language and method of education. If certain aspects of translation do not sit well with you, as a native speaker, I understand. But it does not change the genuineness of other french speaking non-natives. 
We all were going about making things work, having a combative attitude towards the work is okay. But towards the make up of the persons involved is not fair. 
Ivory Coast (Been here) Dahomey (currently Benin) French Sudan (currently Mali)
Guinea. Mauritania. Niger. Senegal. Upper Volta (currently Burkina Faso) Are francophone. We have visited these countries and communicating in the french language gives us the confidence to make attempts. We may not be perfect, but a true cooperative spirit is one that **comes to our aid** and helps out to ensure **the aim is met.**
Maybe out of goodwill and due process, but using terms that reduce the efforts affect morale and kill our love for the work.

**Comment by Pionelle** [comment]
@dckc On the with-holding all of my rewards based on irregularities on this. I find that a bit unfair, but if it is the rule. It must stand then, shouldnt it? I only found of this today and I was left confused since the other works were unrelated to this. 
But then you mention what had to be done. 
But it still came to me as a surprise that I had to be punished even for the good works I had done in other areas of RChain.

**Comment by dckc** [comment]
Since @BelovedAquila removed that May 8 vote, I removed my slashing vote. Likewise with @Pionelle .

Stay tuned to [reward votes on this issue](https://rewards.rchain.coop/index.php?-action=related_records_list&num=%3D653&-relationship=RewardVotes&-table=issue&-ui-root=main-content&-sort=num+desc&-cursor=0&-skip=0&-limit=30&-mode=list&-related%3Asort=slash+desc) for slashing status.

**Comment by BelovedAquila** [comment]
@dckc thank you very much, I appreciate. I appreciate your efforts in seeing things go well in the ways you can, the issues which ensued here wasn't pre-planned , and I haven't really been on the best side with my reaction to it, one thing led to another,all of which I am very sorry, for any disregarding statement made by me in the course of getting an understanding, I am sorry. In whatever way it might have affected the coop in general negatively, I render my apologies, and I would see to it that  subsequent collaborations doesn't give any rise to the questioning of my integrity and that of the issues worked on. 
@dckc I am sorry for the ways I posed disrespect or disregard of  you, you are appreciated and your efforts are,please Pardon. Thank you

**Comment by dckc** [comment]
OK, now that we're back to a civil exchange, let's review:
 - Translation check-list: "several reviewers are involved (assign the ticket to them)" yet only 1 person is assigned since @truffard stepped aside May 11.
   - Perhaps that's an administrative detail and Pionelle is a second reviewer, but
   - I don't see an answer to kitblake's May 9 question about why you deleted the comment from @truffard
 - 0.2 is already obsolete and yet the checklist atop this issue says the source document is stable
 - This issue wasn't even posted until May 2. Why was the bounty claimed in the April pay period?
 - how does the audience find it? I don't see an answer to my question from May 9.
 - Did you coordinate with the authors? Do they want a French translation?
   - A typical way to coordinate with the authors, as well as get the document in a place where the audience can find it, now that the tutorial is maintained in github, is to submit a pull request. For example: https://github.com/rchain/rchain/pull/867 for a German translation. Note how that pull request is still outstanding, meaning it's not clear that the authors want a German translation. And the norm is that one does not claim a reward until a pull request is accepted ("merged"). (I discussed this with Medha during work on #273, but it seems we didn't write it down explicitly.)
 - "source: Diploma" diploma in what? from what institution? (This clarification to the translation checklist was discussed in a recent RAM meeting. I changed ISSUE_TEMPLATE.md 4 days ago.)

**Comment by dckc** [comment]
@Jake-Gillberg , I realized in conversation with @ICA3DaR5 that there's still a https://developer.rchain.coop/  > RHOLANG SPECIFICATION > https://developer.rchain.coop/assets/rholang-spec-0.2.pdf link.

The tutorial has moved on from 0.2, but I guess the spec has not.

The question of maintenance going forward remains.

**Comment by Jake-Gillberg** [comment]
From talking with Mike Stay about this document I got the quote:  "...The
document ... is only of historical value; it has too much philosophizing
and not enough detail about semantics for a proper language specification.
We have a contractor working on a formal operational semantics for Rholang
using K framework. We'll add commentary to it, but the majority of the new
document will be generated from the K code."

**Comment by Jake-Gillberg** [comment]
If it is still linked on developer.rchain.coop then I guess I could see a
case for translation? Though I wouldn't advocate for it ¯\_(ツ)_/¯

**Comment by BelovedAquila** [comment]
@dckc 
- would assign the ticket soon
       - I made a mistake ignorantly  in deleting truffard's comment, never saw it as wrong then, and it was deleted because I perceived the comment as regards to the reviewing, its not to be there, and we under a collaborative agreement, agreed on not filling the Github issue with comments with the aim of making it smart, we agreed on having an in house contributions or comments as regards to any point that's to be made about the issue,rather we should concentrate on making an effective doc and posting it.so finding that comment, I deleted it perceiving it wasn't supposed to be there as agreed and he might not have understood. Never knew its  wrong.
- the check list on the document I supposed had been there before it became obsolete. 
- yes actually the issue wasn't  created till may 2,but I started working on it early week of April with the intention of getting it done with in April, but resulting from the delays of finding github French collaborators to review and meet the translation requirements on the issue,  it took till may 2 to open it .and realizing the budget sheet for April  was still open by then, I decided on the budget placements.
- I actually followed other issues with hope that  the target area placed was gdrive, felt that was where it was to be submitted, but would have  placed it in the actual target if I knew where else. And I tender my apologies as having not realized the access wasn't opened. 
- I actually never came across all of that, safe when I heard @ICA3DaR5 mention something about pull request which I intended looking to,  knowing about and returning a response feedback. I still don't really understand the pull request yet, I wish to be enlighten more so I could respond. 
-The B.A in French from Nnamdi Azikiwe University, Delf certificate Ministry of National Education France

**Comment by dckc** [comment]
> ... something about pull request  ...

That applies more to the rholang tutorial. I have been getting the tutorial confused with the spec. The spec is not maintained in github.

I think the source form of the spec is a google doc... well, that's even older: [Rholang Spec (0.1): 2016-08-03](https://docs.google.com/document/d/1gnBCGe6KLjYnahktmPSm_-8V4jX53Zk10J-KFQl7mf8/edit#heading=h.k4bk2akncduu) cited from [rchain/reference](https://github.com/rchain/reference).

In any case... for the benefit of future collaborators, in addition to .pdf, would you please share your work in editable form? (google doc link, .docx, .rtf, etc.)

> I actually followed other issues with hope that the target area placed was gdrive ...

Typically, the target is right next to the original. This is another reason to coordinate with the authors: to ensure that the translation is available alongside the original. These days, it looks like the main place the 0.2 spec is featured is developer.rchain.coop. @KellyAtPyrofex do you know how documentation links from developer.rchain.coop are managed? Would you like to have a french version there?

Another possibility to reach the audience would be some existing place that's popular for francophones to get RChain news. Even a blog.

As to the rest... it looks like you have answered the outstanding questions. Thanks.

**Comment by BelovedAquila** [comment]
Alright, thank you very much.
>In any case... for the benefit of future collaborators, in addition to .pdf, would you please share your work in editable form? (google doc link, .docx, .rtf, etc.)<

Alright, will do that.

**Comment by BelovedAquila** [comment]
Issue completed.
Please translation guides your attention is needed @ICA3DaR5 @michaelizer @zero-andreou

**Comment by ICA3DaR5** [comment]
@BelovedAquila You consider [this](https://drive.google.com/drive/folders/0BwX0krsxHncTUjNKUnZuOVZGLWc) completed and worthy of $3000?

Examples of poorly written content:
1. 
![7](https://user-images.githubusercontent.com/34237682/42404717-592ee560-8194-11e8-98c1-57e1626c8bb1.png)
2.
![6](https://user-images.githubusercontent.com/34237682/42404718-595a7266-8194-11e8-8e2e-202b63e805ef.png)
3.
![5](https://user-images.githubusercontent.com/34237682/42404719-59878f26-8194-11e8-9231-532b1fa6b934.png)
4.
![4](https://user-images.githubusercontent.com/34237682/42404720-59ae7dc0-8194-11e8-9d0c-59ab894542ce.png)
5.
![3](https://user-images.githubusercontent.com/34237682/42404721-59dcab64-8194-11e8-8ed3-8a51074ba3fd.png)
6.
![2](https://user-images.githubusercontent.com/34237682/42404722-5a088914-8194-11e8-84a7-41e483fe03fe.png)
7.
![1](https://user-images.githubusercontent.com/34237682/42404723-5a40bc58-8194-11e8-96ae-89b5fd73eb37.png)

...and more.

**Comment by truffard** [comment]
Finally you begin to understand when I said that those "translators" have a very basic command of the french language. Whats up with the sugar (sucre) above in §3 ? Pretty funny though.

**Comment by BelovedAquila** [comment]
@ICA3DaR5 are you underestimating the doc as poorly written on the basis that we followed the way it was written in the original doc? I will adjust the budget. 
@truffard aside from the fact that you are ok with ad hominem contrary to norm and good at hasty exaggerated conclusions, you made same good observation which I did, just that you are asking a right question to the wrong person, that question I supposed should go to  the authors of original doc. 
![img_20180707_071322_192](https://user-images.githubusercontent.com/34511117/42407486-559063f4-81b5-11e8-9035-60d0e8893783.JPG)
Yeah, right?

**Comment by BelovedAquila** [comment]
Ok @ICA3DaR5 the examples given are ok, but it's different from the original doc, the dark background on the codes and all wasn't there, so it's like suggesting that we don't follow the way the original doc is, it's like suggesting is ok adding effects and that wasn't in consideration when we worked on the doc.and yes, the codes seems technical as it's appearing to be.

**Comment by philipandri002** [comment]
Wow!!! It seem to me like there is no end to the controversy.. Like I said to @ICA3Da5 @BelovedAquilla maybe is time to end this unpleasant dispute and move on.. I think the best way to resolve situations like this is we need to get both opposing opinions to either shift group or just make some little compromise..

One major thing has been achieved and that is everyone now have a clearer picture of what the guides are here for and are doing a great job to instill discipline, decorum and utmost sincerity.

@truffard it seem to me that your most Interest on this controversy is to prove a personal point and I believe that already has been achieved, its time to stop the fight and focus on the big goal, "RChain coop"and how we can move to greater height and do bigger things for the coop.

Thanks....
Frank Nnalue

**Comment by BelovedAquila** [comment]
@ICA3DaR5 [HERE](https://docs.google.com/document/d/1Rqo_INaZ6lHIbVeUM02WGelH8mK8rIwOq9e166Z-oi4/edit?usp=drivesdk)

**Comment by ICA3DaR5** [comment]
@Jake-Gillberg 

What do you think about this issue now that a month has passed? Check the above comment by @BelovedAquila 

Are you endorsing it?

**Comment by BelovedAquila** [comment]
@ICA3DaR5 please can I now get vote's on this issue?

**Comment by ICA3DaR5** [comment]
@BelovedAquila I am not a guide anymore.

cc @AyAyRon-P @pavlos1851

**Comment by BelovedAquila** [comment]
Alright,thanks @ICA3DaR5
@AyAyRon-P and @Pavlos1851 please can I get votes on this issue?

**Comment by AyAyRon-P** [comment]
After review this is what I read and now know based on all of the comments and my own research into the issue:

1) This is an old document and has been well before it was completed
2) There are several comments that indicate to her that this document is either a) not needed at this point b) only of historical value 
3) This is now being translated by a contractor using K framework 
4) The quality is not up to our technical standard of translation quality
          *****IF this is still an issue I will have a colleague of mine who is from Massy, France check the translation for quality and accuracy****

I can't  vote on an issue that has insufficiently met the requirements and has for some time.  Although I am now the guide it seems that none of my predecessors find this document suitable for translation. 

@pavlos1851 what are your thoughts?

**Comment by pavlos1851** [comment]
@AyAyRon-P I agree with all the points that you've made.
Had this been done right the first time round then everything would have been ok. Voting for this now (3 full months after the creation of the issue) would just be a waste of the coop's resources. I am closing this issue.

**Comment by BelovedAquila** [comment]
@Pavlos1851 yes, actually so many developments have been undertaken in the course of making the doc to required quality, you are almost completely right. But this, 

>Had this been done right the first time round then everything would have been ok <

 it' an unfair and faulty conclusion, I don't know if you had put into consideration what an ISSUE is before now? 
@AyAyRon-P this is still an issue,please you may go ahead to have your colleague check on it, if necccesary
.
I consider It note worthy that aside this docs, all other translated vital docs of the coop,are not just translated for the now or moment of its original publication,neither are they of value for just the time being,They are achieved for future references. So questioning this docs value, simply amazes, except there are no need for future references, for the benefit of present and prospective future members.

**Comment by AyAyRon-P** [comment]
This is the FINAL CLOSING of this project. 

All arguments as to why it should be reopened again are invalid. Let me reiterate the reasons why I am closing this: 

**1. This is an old document and has been well before it was completed**
2. There are several comments that indicate to her that this document is either a) not needed at this point b) only of historical value
3. This is now being translated by a contractor using K framework
4. The quality is not up to our technical standard of translation quality
 *IF this is still an issue I will have a colleague of mine who is from Massy, France check the translation for quality and accuracy

I can't vote on an issue that has insufficiently met the requirements and has for some time. Although I am now the guide it seems that none of my predecessors find this document suitable for translation.

Moving forward, I understand we all want to contribute in the best way we can. We want to lend our skill set in a way that is rewarding to ourselves and provides growth to RChain. However to achieve this, I invite any contributor to think more critically and ask the difficult questions before you start down a path that ultimately leads to, in this case,  nowhere. 


@dckc @pavlos1851

**Comment by pavlos1851** [comment]
@AyAyRon-P :+1:
