### ISSUE TITLE
Stable Coins on the RChain Platform

### ISSUE THREAD

**Issue by iamcoderisk** [rchain/bounties#655]
Since regular people could send money anywhere around the world without any middlemen, instantly, and at an extremely competitive rates as compared to the existing financial systems. However, they'd be a need to get in touch with some of the e-commerce companies in Nigeria, having a partnership terms with them so that they'd see a more reasonable need of using Rchain crypto  as a medium of purchase or as an alternative to bitcoin and Naira. I see this as one of the ways of buying the minds of the people. Just imagine jumia, konga, myshayo,obeezi and commerce using rchain crypto it means that as we are growing, our audience or users will also grow alongside.
Please if the idea is okay and feasible let's work on it.

### Task

*Writing a standard proposal to jumia, konga, dealdey and other e-commerce platform in Nigeria for the acceptance of Rchain Special currency (coin):*

**Comment by philipandri002** [comment]
This is a beautiful idea and I also think, it is strategic. However more insight and ideas will make it truly achievable.
I truly believe we can work on this.

There is a need to either partner with big coperations in African or leading indigenous or local online business here in Nigeria

**Comment by casanwugo** [comment]
@iamcoderisk,, you have a very valid point and must say that this topic is highly interesting. But permit me to remind you, that crptocurrency is yet to be fully accepted in the Nigeria market as it is yet to be licensed or regulated by the CBN.

A “stable coin” is a cryptocurrency that is pegged to another stable asset, like gold or the U.S. dollar. It's a currency that is global, but is not tied to a central bank and has low volatility. ... The adoption of stable coins will be be a catalyst to the new decentralized internet becoming mainstream.

However, the RChain directors and collaborators alike might need to look into this, and find a way to conquer this territory, as RChain is on its own a strong community!

**Comment by allancto** [comment]
@casanwugo , @iamcoderisk , can you give us a short report or reading list to understand stable coin and peg more? I would suggest a good starting point the Medium article by @nashef. If you have any trouble finding it let me know.

Allan

**Comment by casanwugo** [comment]
@allancto, Stablecoins by all measures have been a success, they just need to continue succeeding. Maker Dai is great, adoption on exchanges is already continuing at a decent rate (idex, radar relay, etc.). Just need more awareness and for the concept not to be dismissed by the average crypto enthusiast.

What are stablecoins?

In most parts of the world, there is no such thing as a stable form of money. Especially in cases of hyperinflation, as it currently is the case in Venezuela, we can really experience the importance of a stable currency. Even fiat currencies such as the US Dollar and the Euro are subject to fluctuating exchange rates, diminishing purchasing power, and inflation. However, these fluctuations are usually so small that we can still use these government-issued currencies on a day-to-day basis.

These fluctuations are amplified in the realm of cryptocurrencies which are subject to massive volatility, making them both attractive to speculators and impractical for mainstream use. An ideal cryptocurrency is stable in its purchasing power or is at most slightly inflationary as to incentivize the owners to spend their coins rather than holding on to them. This ideal cryptocurrency is also known as a “stablecoin”. In their most simplistic form, stablecoins are simply cryptocurrencies with stable prices measured in fiat currency.

“A stablecoin is a cryptocurrency that is often pegged to another stable asset, like gold or the U.S. dollar. It’s a currency that is global, but is not tied to a central bank and has low volatility. This allows for practical usage of using cryptocurrency like paying for things every single day.” Sherman Lee
A perfectly engineered stablecoin is the key to achieve all three essential properties of a currency.

Medium of exchange (ability to trade goods and services without bartering)
Store of value (means of maintaining wealth over time)
Unit of account (measurment unit to define and compare market values)

Why are stablecoins important?

For any currency, stability is crucial to trade goods and services without the risk of either the buyer- or seller-side losing value as a result of the price volatility. For cryptocurrencies specifically, price volatility prevents mainstream adoption of applications built on top of the cryptocurrency protocols.

“Any application which requires a low threshold of volatility to be viable on a blockchain, consumer loans for example, simply cannot be denominated in a currency which fluctuates 10–20 percent in a day, like Bitcoin and Ether.” Gregory DiPrisco from MarkerDAO.

For example, it is hard to design a decentralized insurance solution, derivatives or prediction markets if the underlying cryptocurrency changes significantly over short periods of time. The adoption of stablecoins will therefore be a catalyst to the new decentralized internet becoming mainstream.

I hope this short piece helps.

Well, here is what the Medium has to say about bringing stablecoins to the next level; 

The extraordinary expansion of the cryptocurrency markets leads to the need for a stable digital currency, a currency that can be a safe haven in fiat currency terms, without exposure to the volatility risk of the market while being a means of exchange for market participants.

The prime function of a stablecoin is stability.

For a currency, to function as a medium of exchange, it must represent a standard of value accepted by all parties for the short and medium term. To be used and exchanged as “unit of account” people are looking for a stablecoin because they want to be sure its value tomorrow will be predictable and close to today’s value.

This criterion favors fiat-backed tokens as they will track the price of the underlying asset rather than other digital assets and therefore most of them are easy to value.
Stablecoins already exist, the best-known being Tether. Their cryptocurrency USDT is pegged to the US Dollar. It was recently announced that Tether received subpoena from the U.S. Commodity Futures Trading Commission (CFTC). Because stablecoins users are looking for a safe haven, they are particularly demanding in terms of transparency on banking relationships (tier 1 or tier 2 banks) and on regular access to external auditing. According to recent press releases, the current solutions do not follow the transparency standards that prevail in the traditional financial world. Everyone agrees there is room for improvement.

Thanks for reading.

**Comment by jasoncruzzy** [comment]
@iamcoderisk @philipandri002 @casanwugo  yes this will definitely improve Rchain but i think that should be done in the nearest future,  we should be a little on this issue and focus more on awareness and publicity of the Rchain community most especially in africa in that way it will be much more easier for the 'e-commerce'  to accept our proposals and include us as a 'stable coin'

**Comment by allancto** [comment]
I removed the Africa keyword because this project has implications worldwide.

**Comment by jasoncruzzy** [comment]
@allancto If you go read the 'task' on this issue. The proposal is specific on "Nigeria" rather than Africa/Global.

**Comment by allancto** [comment]
**Purpose**
Education- increase the knowledge within RChain about stable coins and how they may be used. Generate ideas- how can stablecoins on RChain benefit individuals worldwide. 

**Format**
Guided study group. One guide plus 5-10 students. Guide should have general background but not be an expert in the domain, guide will learn along with the entire group. 

Guide will be responsible for finding materials, creating assignments, leading discussions. Aim to include participants from many geographical areas. Guide may choose to invite speakers, for instance from existing stablecoin projects. 

**Product** 
Visible product will include materials other coummunity members can draw upon- links / bibliography, essays/ position papers written by the team, calculators or simulations, and so on. Shared folder accessible here:
https://drive.google.com/open?id=1MMPWFheT-KLvrqjH6pNE7oE1of_NSCXR

*Describe how the building and implementation of this task will benefit the RChain Membership* 
Membership community with knowledge in this domain. 

*Estimated Budget of Task:* **$[3000]**  \
$200 for each participant, additional $800 for participants who serve in the role of guide. Total for this team, ~$3000. 
Expectations: each participant should expect to spend about 10 hours of time on this project. Guides should expect to spend significantly more time.

*Estimated Timeline Required to Complete the Task:* **[2 weeks]**  \
First week:
Second week:

*Measure of Completion:* **[Guide determines]**
Google docs folder containing essays, bibliography and other products, as above. 
Repository link is [HERE]([https://drive.google.com/open?id=1MMPWFheT-KLvrqjH6pNE7oE1of_NSCXR]). 

-----  \
***Disclaimer***
All work and rewards are subject to member review and budgetary oversight. Participation is NOT a guarantee of reward. 

***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by allancto** [comment]
@jasoncruzzy, above is an issue statement to consider. if a nigeria specific proposal is desired, we can split this into two issues.

**Comment by allancto** [comment]
@philipandri002 I've copied and pasted your post above into the repo "Essays 0. Why are Stablecoins of Interest to Me?"
https://drive.google.com/open?id=1ic7j1dx4f-lVbnLXRP3NJLYFbdkdvW2E

Let me know if you have any trouble getting to this folder or accessing your document. 

Thanks!
Allan

**Comment by jasoncruzzy** [comment]
@ allanco i just went through the link without no troubles

**Comment by Keaycee** [comment]
@iamcoderisk  please accept this invite 

- [ ] Watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [ ] Join rchain@googlegroups.com to get access to documents of RChain https://groups.google.com/forum/#!forum/rchain/join
- [ ] Join github/rchain/bounties in order to contribute https://github.com/rchain/bounties/invitations
- [ ] Fill out the RAM registration form https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform 
- [ ] Collaborate in all kind of issues https://github.com/rchain/bounties/issues
- [ ] Collaborate in development https://rchain.atlassian.net/browse/OPS-31?jql=labels%20%3D%20bounty
- [ ] Fool around with our Bounty App https://rewards.rchain.coop/
- [ ] Read about collaborating https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [ ] Read about our decentralized bounty system. https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App
- [ ] Join RChain Coop by signing up for membership http://member.rchain.coop/
- [ ] Claim your reward: https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
- [ ] fill out a W8 https://www.irs.gov/pub/irs-pdf/fw8ben.pdf
- [ ] read W8 instructions https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing
- [ ] or fill out a W9 https://www.irs.gov/pub/irs-pdf/fw9.pdf
- [ ] W9 instructions https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit

**Comment by Keaycee** [comment]
@iamcoderisk You've got a prospect in your point. I like the idea, but we need to understand that there are lots of cryptocurrencies which are yet to be to recognized especially in Nigeria. Bitcoin and Ethereum are known globally and some countries accept it as a medium of exchange. In Nigeria, Financial and other institutions are yet to accept this coin as a means of exchange. A stable coin, is not like every other crypto coin, because it relies or it's been linked on others asset that has already been given value, or has value and also accepted as a medium of exchange in the world. For a stable coin on RChain is a nice idea, but that will make individuals and some investors to hold the coin as an asset. 
However, some potential investors and individuals may prefer to hold it because of the future valuation.

**Comment by TrenchFloat** [comment]
There seems to be no action on @allancto 's proposal after over two weeks.

**Comment by allancto** [comment]
@TrenchFloat thank you for adding wontfix- this is an issue we may wish to consider in the future but on hold for now. We had hoped to find a guide/ team leader within this task who would be able to lead the team through researching and learning about stable coins. This has not happened yet. 

Many of the members who have provided input into this issue here are geographically from Nigeria. At the RAM meeting 2018 0523 there was quite a bit of discussion of how to enable contributions by members from Africa in general and Nigeria in particular. @Ojimadu volunteered to choose a format so that all interested members may explore project ideas. What special skills, perspectives and opportunities does this demographic of members bring, and what projects might be inspired that create unique value for our Cooperative.
