### ISSUE TITLE
Update the CONTRIBUTING/CONTRIBUTING_GR.md file

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#676]
# Issue

## Content
- [CONTRIBUTING_GR.md](https://github.com/ICA3DaR5/bounties/blob/master/CONTRIBUTING/CONTRIBUTING_GR.md)

## Tasks
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Greek.
- [ ] Create a [Pull Request]()

## Collaborators
- @ICA3DaR5: 0%
- @zero-andreou: 0%
- @thiefinshadows : 0%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the CONTRIBUTING.md file in other languages means good marketing.

*Estimated Budget of Task:* **$50**  \
*Estimated Timeline Required to Complete the Task:* **17 days**  \
*Measure of Completion:* **0%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #540, #472, #497, #585, #597, #621, #586, #688, #650 
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: keep it up to date forever, for $0

**Comment by ICA3DaR5** [comment]
Closing this, since no work has been done.
