### ISSUE TITLE
Update the CONTRIBUTING/CONTRIBUTING_IT.md file 

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#684]
# Issue

## Content
- [CONTRIBUTING_IT.md](https://github.com/rchain/bounties/blob/master/CONTRIBUTING/CONTRIBUTING_IT.md)

## Tasks
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Italian.
- [ ] Create a [Pull Request]()

## Collaborators
- @Staff91: 10%
- @akhs13 : 0%
- @Chris-Arv  : 0%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the CONTRIBUTING.md file in other languages means good marketing.

*Estimated Budget of Task:* **$0**  \
*Estimated Timeline Required to Complete the Task:* **7 days**  \
*Measure of Completion:* **10%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #645 
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: keep it up to date forever, for $0

**Comment by ICA3DaR5** [comment]
This is 2 days overdue!
