### ISSUE TITLE
Translate "RChain Weekly Update (Debrief 75) — 02 May" blog post to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#686]
# Issue

## Original (English) Content
- [RChain Weekly Update (Debrief 75) — 02 May](https://medium.com/rchain-cooperative/rchain-weekly-update-b3b9fbd480f7)

## Translated (Greek) Content
- [ ]()

## Tasks
- [x] Copy the original (English) content to the [RChain Cooperative — Greek](https://medium.com/@rchain.gr) Medium blog.
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Greek.
- [ ] Post the translated (Greek) content to the [RChain Cooperative — Spanish](https://medium.com/@rchain.gr) Medium blog.

## Collaborators
- @ICA3DaR5: 50%
- @zero-andreou: 50%
- @thiefinshadows : 0%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$400**  \
*Estimated Timeline Required to Complete the Task:* **2 days**  \
*Measure of Completion:* **0%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #540, #472, #497, #585, #597, #621 
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by Murphy6** [comment]
That will really promot the community in a big way.

**Comment by ICA3DaR5** [comment]
@Murphy6 We've translated almost all the Medium blog posts up to now.
