### ISSUE TITLE
Translate " RNode v0.3.1 introduces the RChain consensus protocol" blog post to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#688]
# Issue

## Original (English) Content
- [RNode v0.3.1 introduces the RChain consensus protocol](https://medium.com/rchain-cooperative/rnode-v0-3-1-introduces-the-rchain-consensus-protocol-23e67666ba82?source=collection_home---6------1----------------)

## Translated (Greek) Content
- [Το RNode v0.3.1 συμπεριλαμβάνει το πρωτόκολλο συναίνεσης του RChain](https://medium.com/@rchain.gr/%CF%84%CE%BF-rnode-v0-3-1-%CF%83%CF%85%CE%BC%CF%80%CE%B5%CF%81%CE%B9%CE%BB%CE%B1%CE%BC%CE%B2%CE%AC%CE%BD%CE%B5%CE%B9-%CF%84%CE%BF-%CF%80%CF%81%CF%89%CF%84%CF%8C%CE%BA%CE%BF%CE%BB%CE%BB%CE%BF-%CF%83%CF%85%CE%BD%CE%B1%CE%AF%CE%BD%CE%B5%CF%83%CE%B7%CF%82-%CF%84%CE%BF%CF%85-rchain-98c9283ca668)

## Tasks
- [x] Copy the original (English) content to the [RChain Cooperative — Greek](https://medium.com/@rchain.gr) Medium blog.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Greek.
- [x] Post the translated (Greek) content to the [RChain Cooperative — Greek](https://medium.com/@rchain.gr) Medium blog.

## Collaborators
- @ICA3DaR5: 50%
- @zero-andreou: 50%
- @thiefinshadows : 0%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$170**  \
*Estimated Timeline Required to Complete the Task:* **3 days**  \
*Measure of Completion:* **100%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #540, #472, #497, #585, #597, #621, #586 
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____
