### ISSUE TITLE
Translate rholangtut-0.3.md to Croatian

### ISSUE THREAD

**Issue by Howsoonisnow** [rchain/bounties#690]
# Issue

## Original (English) Content
- [rholangtut-0.3.md](https://github.com/rchain/rchain/blob/master/docs/rholang/rholangtut-0.3.md)

## Translated (Croatian) Content
- [rholangtut-0.3.hr](https://drive.google.com/drive/u/0/folders/0BwX0krsxHncTUjNKUnZuOVZGLWc)

## Tasks
- [x] Download the original (English) content.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Croatian.
- [ ] Create a [Pull Request](https://github.com/rchain/rchain/pull/789).

## Collaborators
- @Howsoonisnow 
- @Internautneven 
- @MarioPolo Polo 
## Rewiers
- @ibrica 
- @tgrospic 

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$1100**  \
*Estimated Timeline Required to Complete the Task:* **60 days**  \
*Measure of Completion:* **100%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #125 #382 #449 #546
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: keep it up to date forever

**Comment by Howsoonisnow** [comment]
We have completed the translation.

**Comment by ICA3DaR5** [comment]
Please leave this open until the Pull Request is merged.

**Comment by Howsoonisnow** [comment]
Ok

**Comment by pavlos1851** [comment]
Hi @tgrospic. Please verify your membership as per [the wiki](https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App#connect-your-coop-membership).

**Comment by AyAyRon-P** [comment]
@tgrospic @Howsoonisnow @MarioPolo @InternautNeven 

What is the status of this issue? Have you completed the PR that was requested back in May by Donald? 

cc @pavlos1851

**Comment by Howsoonisnow** [comment]
We are working on it. It will be finished soon.
Regards!

**Comment by dckc** [comment]
rewarded in 201805
