### ISSUE TITLE
Translate 5 Medium blog posts to Ukrainian

### ISSUE THREAD

**Issue by irynapopova61** [rchain/bounties#710]
# Issue

## Original (English) Content
- [Welcome Kenny Rowe!](https://medium.com/rchain-cooperative/welcome-kenny-rowe-c120ac55b404)
- [Resonate and lifeID collaborate](https://medium.com/rchain-cooperative/resonate-and-lifeid-collaborate-da2d22e43df6?source=---------3)
- [RNode v0.3.1 introduces the RChain consensus protocol](https://medium.com/rchain-cooperative/rnode-v0-3-1-introduces-the-rchain-consensus-protocol-23e67666ba82?source=---------2)
- [RChain Weekly Update (Debrief 75) — 02 May](https://medium.com/rchain-cooperative/rchain-weekly-update-b3b9fbd480f7?source=---------1)
- [RChain Weekly Debrief | 9th, May 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-9th-may-2018-687bd7c80ebd?source=---------0)

## Translated (Ukrainian) Content
- [ Щиро вітаємо Кенні Роу!](https://medium.com/@rchain_ukraine/%D1%89%D0%B8%D1%80%D0%BE-%D0%B2%D1%96%D1%82%D0%B0%D1%94%D0%BC%D0%BE-%D0%BA%D0%B5%D0%BD%D0%BD%D1%96-%D1%80%D0%BE%D1%83-44a9c420dc27)
- [Колаборація Resonate та lifeID ](https://medium.com/@rchain_ukraine/%D0%BA%D0%BE%D0%BB%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%86%D1%96%D1%8F-resonate-%D1%82%D0%B0-lifeid-c7c762cbb607)
- [ RNode v0.3.1 представляє протокол консенсусу RChain](https://medium.com/@rchain_ukraine/rnode-v0-3-1-%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D1%94-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB-%D0%BA%D0%BE%D0%BD%D1%81%D0%B5%D0%BD%D1%81%D1%83%D1%81%D1%83-rchain-e4920cefcd68)
- [Щотижневе оновлення RChain (дебріф 75) — 02 травня ](https://medium.com/@rchain_ukraine/%D1%89%D0%BE%D1%82%D0%B8%D0%B6%D0%BD%D0%B5%D0%B2%D0%B5-%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-rchain-%D0%B4%D0%B5%D0%B1%D1%80%D1%96%D1%84-75-02-%D1%82%D1%80%D0%B0%D0%B2%D0%BD%D1%8F-1a67e4ac0e7a)
- [Щотижневий огляд RChain | 9 травня 2018 року ](https://medium.com/@rchain_ukraine/%D1%89%D0%BE%D1%82%D0%B8%D0%B6%D0%BD%D0%B5%D0%B2%D0%B8%D0%B9-%D0%BE%D0%B3%D0%BB%D1%8F%D0%B4-rchain-9-%D1%82%D1%80%D0%B0%D0%B2%D0%BD%D1%8F-2018-%D1%80%D0%BE%D0%BA%D1%83-cbe38a10ca20)

## Tasks
- [x] Copy the original (English) content to the [RChain Cooperative — Ukrainian](https://medium.com/@rchain_ukraine) Medium blog.
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Ukrainian.
- [x] Post the translated (Ukrainian) content to the [RChain Cooperative — Ukrainian](https://medium.com/@rchain_ukraine) Medium blog.

## Collaborators
- @thiefinshadows: 35%
- @irynapopova61: 60%
- @jkost401 : 5%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$1500**  \
*Estimated Timeline Required to Complete the Task:* **10 days**  \
*Measure of Completion:* **100%

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [ ] a track record of quality work on rchain bounties: 
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by casanwugo** [comment]
аскаво просимо Кенні Роу!

**Comment by casanwugo** [comment]
@irynapopova61,,, Nice post! I have translated "Welcome Kenny Rowe" to Ukrainian and posted to medium blog. 

Collaborators please check and verify. Thanks

**Comment by ICA3DaR5** [comment]
@casanwugo You posting a link to the translated blog post would be helpful.

**Comment by casanwugo** [comment]
@ICA3DaR5.... dear friend, thanks for your comment and letting me know that I should have posted a link across. But this is a mutual community so please be careful with your choice of words! This is a learning process for me and I was made to believe that we are all collaborators. Please go easy! I will put the link across or better yet delete the edited write-ups. Thanks all the same.

**Comment by ICA3DaR5** [comment]
@casanwugo I am only saying this to avoid duplication of work.
