### ISSUE TITLE
Translate 5 Medium blog posts to Russian

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#714]
# Issue

## Original (English) Content
- [Welcome Kenny Rowe!](https://medium.com/rchain-cooperative/welcome-kenny-rowe-c120ac55b404)
- [Resonate and lifeID collaborate](https://medium.com/rchain-cooperative/resonate-and-lifeid-collaborate-da2d22e43df6?source=---------3)
- [RNode v0.3.1 introduces the RChain consensus protocol](https://medium.com/rchain-cooperative/rnode-v0-3-1-introduces-the-rchain-consensus-protocol-23e67666ba82?source=---------2)
- [RChain Weekly Update (Debrief 75) — 02 May](https://medium.com/rchain-cooperative/rchain-weekly-update-b3b9fbd480f7?source=---------1)
- [RChain Weekly Debrief | 9th, May 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-9th-may-2018-687bd7c80ebd?source=---------0)

## Translated (Russian) Content
- [Добро пожаловать, Кенни Роу!](https://medium.com/@rchain_ru/%D0%B4%D0%BE%D0%B1%D1%80%D0%BE-%D0%BF%D0%BE%D0%B6%D0%B0%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BA%D0%B5%D0%BD%D0%BD%D0%B8-%D1%80%D0%BE%D1%83-78a23667228d)
- [Соотрудничество Resonate и lifeID ](https://medium.com/@rchain_ru/resonate-%D0%B8-lifeid-%D0%BE%D1%87%D0%B5%D0%BD%D1%8C-%D1%80%D0%B0%D0%B4%D1%8B-%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%B8%D1%82%D1%8C-%D0%BE-%D0%BD%D0%BE%D0%B2%D0%BE%D0%BC-%D1%81%D0%BE%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5-de946522ee3b)
- [RNode v0.3.1 вводит консенсусный протокол RChain](https://medium.com/@rchain_ru/rnode-v0-3-1-%D0%B2%D0%B2%D0%BE%D0%B4%D0%B8%D1%82-%D0%BA%D0%BE%D0%BD%D1%81%D0%B5%D0%BD%D1%81%D1%83%D1%81%D0%BD%D1%8B%D0%B9-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB-rchain-55aa2bf57ab1)
- [Еженедельное обновление RChain (Подведение итогов 75) — 02 мая ](https://medium.com/@rchain_ru/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%BF%D0%BE%D0%B4%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%82%D0%BE%D0%B3%D0%BE%D0%B2-75-02-%D0%BC%D0%B0%D1%8F-7904527149be)
- [Еженедельное обновление RChain | 9 мая, 2018 г. ](https://medium.com/@rchain_ru/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-9-%D0%BC%D0%B0%D1%8F-2018-%D0%B3-b00ff8ba6a65)

## Tasks
- [x] Copy the original (English) content
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Russian.
- [x] Post the translated (Russian) content to the [RChain Cooperative — RU](https://medium.com/@rchain_ru) Medium blog.

## Collaborators
- @qelentium: 85%
- @thiefinshadows : 10%
- @pavlos1851  : 5%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$2000**  \
*Estimated Timeline Required to Complete the Task:* **11 days**  \
*Measure of Completion: *100*%

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [ ] a track record of quality work on rchain bounties: 
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: 30/05/2018

**Comment by ICA3DaR5** [comment]
**RCHAIN; THE FUTURE OF DECENTRALIZED INTERNET** is not an RChain blog item as you mentioned in the **For Translators** section.

**Comment by qelentium** [comment]
@ICA3DaR5 my fault, redone
