### ISSUE TITLE
Translate "RChain Weekly Debrief - 9th, May 2018" blog post to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#715]
# Issue

## Original (English) Content
- [RChain Weekly Debrief - 9th, May 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-9th-may-2018-687bd7c80ebd)

## Translated (Greek) Content
- [Εβδομαδιαία Ενημέρωση του RChain (Debrief 76) – 9 Μαΐου 2018](https://rchain.gr/t/rchain-debrief-76-9-2018/34)

## Tasks
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Greek.
- [x] Post the translated (Greek) content to the [RChain's Greek Community](https://rchain.gr/c/%CE%99%CF%83%CF%84%CE%BF%CE%BB%CF%8C%CE%B3%CE%B9%CE%BF) website.

## Collaborators
- @ICA3DaR5: 50%
- @zero-andreou: 50%
- @thiefinshadows : 0%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$600**  \
*Estimated Timeline Required to Complete the Task:* **5 days**  \
*Measure of Completion:* **100%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #244, #265, #286. #287. #288, #292, #299, #345, #363, #390, #447, #459, #475, #497, #540, #585, #586, #597, #621, #650, #686, #688.
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____
