### ISSUE TITLE
Translate "RNode v0.3.1 introduces the RChain consensus protocol" - "RChain Weekly Update (Debrief 77) -16 May 2018" to German

### ISSUE THREAD

**Issue by gsofianidis** [rchain/bounties#732]
# Issue

## Original (English) Content
- [RChain Weekly Update (Debrief 77) -16 May 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-77-16-may-2018-5ecfa806933f)
- [RChain Weekly Debrief - 9th, May 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-9th-may-2018-687bd7c80ebd)
- [RChain Weekly Update (Debrief 75) — 02 May](https://medium.com/rchain-cooperative/rchain-weekly-update-b3b9fbd480f7)
- [RNode v0.3.1 introduces the RChain consensus protocol](https://medium.com/rchain-cooperative/rnode-v0-3-1-introduces-the-rchain-consensus-protocol-23e67666ba82)

## Translated (German) Content
- [RChain Wöchentliches Update (Nachbesprechung 77) -16. Mai 2018](https://medium.com/@rchain_de/rchain-w%C3%B6chentliches-update-nachbesprechung-77-16-mai-2018-5e7c04f9a273)
- [RChain Wöchentliche Nachbesprechung | 9. Mai 2018](https://medium.com/@rchain_de/rchain-w%C3%B6chentliche-nachbesprechung-9-mai-2018-2ac32673759b)
- [RChain Wöchentliches Update (Debrief 75) — 02 Mai](https://medium.com/@rchain_de/rchain-w%C3%B6chentliches-update-debrief-75-02-mai-ea559b5b157f)
- [RNode v0.3.1 führt das RChain Consensus-Protokoll ein](https://medium.com/@rchain_de/rnode-v0-3-1-f%C3%BChrt-das-rchain-consensus-protokoll-ein-b2fc081405c1)

## Tasks
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and German.
- [x] Post the translated (German) content to [German Medium Blog](https://medium.com/@rchain_de).

## Collaborators
- @gsofianidis : 50%
- @amaliasof  : 50%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* $1600  \
*Estimated Timeline Required to Complete the Task:* 6 days  \
*Measure of Completion:* 100%

—  \
*Legal*  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because 
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [x] a track record of quality work on rchain bounties: #633 

  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is:

**Comment by ICA3DaR5** [comment]
Closing this, it looks complete! Please don't forget to vote!
