### ISSUE TITLE
Translate RChain Weekly Update(Debrief 78) — 23, May

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#751]
### Benefit to RChain

Translation of the RChain Medium blog posts to other languages means  global marketing.
Budget and Objective

Estimated Budget of Task: $[400] Estimated Timeline Required to Complete the Task: [2 days] How will we measure completion? Post on [RChain_Ru Medium Blog](https://medium.com/@rchain_ru/rchain-weekly-update-%D0%BF%D0%BE%D0%B4%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%82%D0%BE%D0%B3%D0%BE%D0%B2-78-23-%D0%BC%D0%B0%D1%8F-c27528512af3)

Legal
Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.

## Original (English) Content
- [RChain Weekly Update(Debrief 78) — 23, May](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-78-23-may-c919bf19a8ed)

## Tasks
- [x] Translate the content.
- [x] Check the spelling.
- [x] Review each other's work.
- [x] Have them reviewed by others with knowledge of English and Russian.
- [x] Post the translated (Russian) content to the [RChain Cooperative (Russian)](https://medium.com/@rchain_ru) Medium blog post.

## Collaborators
- @qelentium : 90 %
- @thiefinshadows : 5%
- @pavlos1851  : 5%

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in Russian
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [ ] a track record of quality work on rchain bounties: 
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: 05/06/2018

**Comment by ddayan** [comment]
Not sure if that's the place to criticise but that's a bit expensive. If we start translating the weekly debriefs to every language it would cost us thousands of dollars. Is anyone measuring the demand for the translations? (youtube and medium offer analytic tools for pages and subtitles).

**Comment by qelentium** [comment]
@ddayan 0,2 per word 1644 word = 328.8 + 70 usd for reviewers

**Comment by ddayan** [comment]
So let's say that from now on people will translate the weekly debriefs to 5 different languages, by the end of Q4 (main-net release) the coop will spend  $400 * 5 * 30 = $60,000. I don't think it's smart to spend the marketing budget on that. Please don't get me wrong I don't think that Russian translations are useless (6% of Russians speak English and you also have population from former USSR countries) just not convinced that it would be effective to spend the marketing budget on weekly debrief transactions.

**Comment by zero-andreou** [comment]
Please use the new [issue template](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md)

**Comment by ICA3DaR5** [comment]
Please use the new **[ISSUE_TEMPLATE](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md)**

Also, from this month forward the cooperative is not going to focus on translations per se. You need to add **value** to your translations. Check **[Allan Cooper's comment](https://github.com/rchain/bounties/issues/746#issuecomment-395944639)**.

**Comment by ddayan** [comment]
any reason to re-open this?

**Comment by ICA3DaR5** [comment]
@ddayan Check my last [comment](https://github.com/rchain/bounties/issues/751#issuecomment-400757584).

**Comment by qelentium** [comment]
@ICA3DaR5 added value (comments and explanations). Reupdated issue template.Can close now?

**Comment by ICA3DaR5** [comment]
@qelentium 

@allancto can tell you more about the added value I guess.

As far as I am concerned just fill the **What about maintenance? (choose one)** section on the issue template and close the issue.
