### ISSUE TITLE
Translate rholang-spec-0.2.pdf to Portuguese

### ISSUE THREAD

**Issue by akhs13** [rchain/bounties#769]
# Issue

## Original (English) Content
- [rholang-spec-0.2.pdf](https://developer.rchain.coop/assets/rholang-spec-0.2.pdf)

## Translated (Portuguese) Content
- []()

## Tasks
- [x] Download the original (English) content.
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Portuguese.
- [ ] Upload the PDF file to Google Drive[]()

## Collaborators
- @akhs13: 80%
- @lopezi  : 20%

---

### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

More people reading the blog posts in other languages means good marketing.

*Estimated Budget of Task:* **$2300**  \
*Estimated Timeline Required to Complete the Task:* **20 days**  \
*Measure of Completion:* **10%**

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source:
       - [x] a track record of quality work on rchain bounties:  #367 #368 #369 #392 #488 #489 #502 #537 #576 #572 #573 #574 #587 #590 #670 #687 #691 #717 #722 
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____
