### ISSUE TITLE
Translate New Blog Posts to French ; Promote on large Media groups.

### ISSUE THREAD

**Issue by casanwugo** [rchain/bounties#949]
### Benefit to RChain

Translation of the RChain blog posts to other languages means good global marketing. Also, reach a larger audience and help expand the community building.

### Tasks :

- [x] Translate the contents to French.

- [x] Add value by including original commentaries (Publisher's review).

- [x] Post both English and French contents on several crypto channels to reach a wider audience.

- [x] Check for views, comments & feedbacks.

 * _English & French Contents will be posted on_ ;

- [x] <a href="https://medium.com/@annchidinma5">@Crypto Medium Blog</a>
 
- [x] <a href="https://rchaincommunity.xyz/">RChain Worldwide Community Forum > French (Français) > Blog</a>

- [x] [BITCOIN Cote d'Ivoire (Facebook)](https://www.facebook.com/bitcoincotedivoire/)

### Original (English) Contents :

- <a href="http://blog.rchain.coop/rchain-debrief-92-rcon3-week/">RCHAIN DEBRIEF 92: VALIDATOR ECONOMICS</a> (871 words)

- <a href="https://blog.rchain.coop/intro-to-design-of-computational-calculi-1/">Intro to design of computational calculi 1</a> (1833 words)

- <a href="https://blog.rchain.coop/rsong-the-future-of-music/">RSONG: THE FUTURE OF MUSIC</a> (716 words)

- [RCHAIN DEBRIEF 93: RCON3](https://blog.rchain.coop/rchain-debrief-93-rcon3/) (195 Words)

- [RChain test net genesis ceremony](https://blog.rchain.coop/rchain-testnet-genesis-ceremony/) (653 words)

- [What's your Must? Dispatch from RCon3](http://blog.rchain.coop/whats-your-must-dispatch-from-rcon3/) (187 words)

### Translated (French) Contents :

- 

-

-

-

-

-

### Collaborators ;

@casanwugo :
@philipandri002 :
@belovedaquila :

### Budget and Objective

_Estimated Budget of Task:_ **$[ 614.55 ]**  
_Estimated Timeline Required to Complete the Task:_ **[3 weeks]**
_How will we measure completion?_ **[ Post *English & French contents* on ; <a href="https://medium.com/@annchidinma5">@Crypto Medium Blog</a>, <a href="https://rchaincommunity.xyz/">RChain Worldwide Community Forum > French (Français) > Blog</a>, and [BITCOIN Cote d'Ivoire (Facebook)](https://www.facebook.com/bitcoincotedivoire/) ]**

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #711, #808, #846, #889 ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by jplepel** [comment]
Is there a market for French translations? Where are these translations posted after completion?

**Comment by luigidemeo** [comment]
This is not necessary

**Comment by casanwugo** [comment]
@jplepel... Asides posting on the community xyz forum, French translations are also posted on - <a href="https://medium.com/@annchidinma5">@Crypto Medium Blog</a>. It's got a number of following and the target audience between. The "Stats" icon shows a total number of views, reads, claps, etc... generated from each published article.

**Comment by jplepel** [comment]
@casanwugo Via the medium blog, there is consistent claps from the same 3 people. The stats icon may only be viewable by the author, could you share those numbers in here? Thanks

**Comment by BelovedAquila** [comment]
@jplepel I think claps isn't enough to determine audience especially as it pertains to media's like medium which doesn't tend to tell who read or viewed, making it however possible that audiences can read without clapping.

**Comment by luigidemeo** [comment]
claps are not sufficient and we have no metrics of viewership. Please present screenshots of the previous articles translated.

**Comment by casanwugo** [comment]
@luigidemeo... These have been answered before now.


"This is necessary"... Because a lot of time,  committment, and hardwork go into posting  French translations. "This is necessary" because language still remains a challenge for businesses to reach a larger audience. Please note that these valuable documents are archived to serve purpose time after time. And in today’s world, it’s important to speak the language of your audience! Our coop need these professional language translation to get higher ROI by keeping the website visitors engaged.

French is official language in 29 countries of the world  brings a need to translate documents in French, because RChain is a global brand.

PS : I'm currently researching on new blogs where the contents will be posted for more views. There is also the addition of original commentaries (publisher's review), as well as posting both English and French versions so that more people can read.

**Comment by AyAyRon-P** [comment]
Because a lot of time, commitment, and hardwork go into something doesn't mean it's necessary and also doesn't mean it's of value to RChain. 

There are 61 countries in which at least 50% of the population speaks [English](https://en.wikipedia.org/wiki/English_language_in_Europe) Further to that point, France is ranked at a level of moderate (ref. <https://www.ef.edu/epi/regions/europe/france/>)proficiency with a score percentage of 54.39%  of it's population understanding English. IF we had hundreds upon hundreds of followers from France or French speaking countries with French developers interested in working with RChain, then and only then would it make any sense to put a bounty on translation. 

You currently have 270 personal followers based on @Viraculous findings in #960 meaning of the 275 million French speaking individuals you have captured .0000001%. 

Translations are suspended indefinitely please see #783 

cc @pavlos1851 @zsluedem @Viraculous

**Comment by philipandri002** [comment]
@AyAyRon-P I find this hypothesis of yours very inaccurate.. 

You say          






> There are 61 countries in which at least 50% of the population speaks English Further to that point, France is ranked at a level of moderate (ref. https://www.ef.edu/epi/regions/europe/france/)proficiency with a score percentage of 54.39% of it's population understanding English. IF we had hundreds upon hundreds of followers from France or French speaking countries with French developers interested in working with RChain, then and only then would it make any sense to put a bounty on translation.           









I see you put on Discord that translating in Chinese is necessary but French is not, only because we do not have hundreds and hundreds of followers. I truly think that is absurd because you actually agreed also on discord that translation overlaps with marketing and if that is true and I agree too, what then is marketing if we already have the people?

The aim of marketing if I may remind you is to reach out to people who don't know about a product to try and bring them to use that particular product.. Marketing is not for only existing customers, in fact marketing primarily is to get fresh clients, customers, users, and or patronage as the case may apply.

RChain isnt different in that philosophy, the aim is to reach new people, penetrate more territories as possible and conquer new frontiers to come join and discover and put to use the RChain platform.

Like I said and will keep saying, marketing is a very broad department for any organization and is also very expensive to run, not only in RChain, but in every vision driven organisation. You can argue this only if you have never worked in an organisation that strives to succeed in a highly competitive market.

French has thousands of  crypto / blockchain enthusiasts / developers who do not and will never understand English language.

French is the official language of 29 countries, means it is the recognised to the speakers even more than their native language. This includes countries in Africa and Europe.

Also, you say that Chinese and Russian are exceptions for translation, but I do not see the hundreds and hundreds of Chinese followers / developers compared to the over 1.4+ billions Chinese populations going by your statistical evaluation you drew you logic for French ( same applies to Russian )..

Finally, like i discussed with Jimscarver and Viraculous Victor on zoom collab, the problem is not translation but the failure and ineffectiveness of the label guides. The guides are not proactive but passive and defensive, they lack ideas to organise and guide their labels to produce efficiency and productivity that will reflect the RChain vision.

Marketing also is a deep mess even as I watch the guides are clueless and inactive with no projection and direction to lead people. 

And I think amongst the translators, "French translations" has being productive in growing following and increasing audience.

**Comment by AyAyRon-P** [comment]
Hi @philipandri002 thanks for taking the time to respond. The problem is we're wasting resources on translations and there is ZERO need for them at this time. 

I invite you to do a bit more research about the need for Chinese translations. We have a sizable community of over 2500 people, we have investors taking part in the validator group, and there are developers on board from China. Can you say the same for native French speakers? Please provide sources, links, and references if you're able to. 

> RChain isnt different in that philosophy, the aim is to reach new people, penetrate more territories as possible and conquer new frontiers to come join and discover and put to use the RChain platform.
Isn't that the idea for almost all blockchain technologies out there? Yet why is we don't see them translating into every possible language? Please find references to prove why we need to translate them other than that same blanket non-response of "just because". 

I've worked in the Oil and Gas industry for several multi-billion dollar companies and they RARELY translate documents unless it's an incredibly high level marketing piece or there is a specific region and audience for it. So yes, I am very familiar with this. What is your experience in marketing for large organizations since we're bringing this up? Have you worked with international marketing teams to develop multi-cultural campaigns and messaging? If you have I'd be interested in knowing more about it. 

Marketing for any organization is almost as if not more important than the product itself. It seems despite our differences of opinion, we do agree that marketing is a mess and that unfortunately guides, like myself, are left to take measures in order to reduce the probability of and to minimize the effects of unwanted or unnecessary issues being generated. The biggest problem I see is the rather than getting our marketing directions from the top down (Patrick and the marketing org) it's coming from the bottom up (RAMs) based on what we think is needed. I have never worked for or been a part of any organization that doesn't give clear direction from the top down because as we both agree, it's a complete mess, wasting both time and money. 

Please let me know when you plan on having this brainstorming meeting. I'd like to be part of the solution if I can for the future of RChain Marketing.

**Comment by Viraculous** [comment]
@AyAyRon-P  I agree with you that there was no need for so many of the translation work but tagging the translation work as a "waste of resources" is what I don't totally agree with you though you can still state why you consider it a "waste of resources". My reason is because you are a label guide and if you had considered those efforts translation efforts as a waste, you would have put a proposal forth as a label guide declaring that you see no value(i.e having taken time consider the audience around this by checking where they were posted) in the translations stating your reasons. 
Secondly don't really consider peoples effort like that to be " wasteful" especially if I am a guide to such works. Translation has benefits its all about who gets and read them like you consider Chinese translations to be needful because the have an audience around RChain. In essence is all about the essence made in harnessing the value. Please see my reply to you in #960.

**Comment by ddayan** [comment]
While I disagree with @AyAyRon-P 's calculation of French speakers, I still don't see any evidence that French translations are needed. If it's a valuable marketing resource then the marketing team should want to use it and therefore sponsor this bounty.

**Comment by AyAyRon-P** [comment]
@ddayan that's what happens when you use the internet - the data is old as soon as the survey is completed. Take a look for yourself. Even across multiple sources that I posted in the #bounties channel the number of French speakers is low.  

@Viraculous I consider it a waste of resources because as you called attention to it yourself in issue #960 that we've spent upwards of $170,000 but to date I don't see where the ROI is to RChain? When I say a waste of resources, I meant in terms of dollars. To be fair, I have only been a translation label guide from mid-July, and in that time I have implemented the [online translation](https://customer.stepes.com/instant-translation-quote/#)to help reduce the speculative bounty members were placing on translations. This process alone has saved the coop thousands in over priced translation bounties. My next action was to create a validation of English proficiency test which I spent hours on, but with talks of removing the label entirely last month I opted not to move forward with that validation process. Where I see the most waste is in time spent. There have been hundreds of hours spent on translations, but none of the issues has someone shown that any interested party asked for these translations, this is all done on the idea that if it's translated it will be read at some time by some one. It's hard to see the value when that person could instead focus their energy writing a unique article in their native language with supporting translations. In my opinion that is the direction and the next step for translations. Translators doing multi-lingual articles with supporting translations to reach that global audience is where there would be value, but a translation for the sake of being translated has none.
